### PR TITLE
Improved logic for dividing rtmp path up into connection and stream part

### PR DESCRIPTION
**Pull request by Lillemanden**
This is a fix for https://github.com/videojs/video.js/issues/2776

### CODE REVIEW

**Comment by pam** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: fc048a05aaadb3a4a18e9af2d2f62541c7d56085
Build details: https://travis-ci.org/pam/video.js/builds/89758704

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by gkatsev** [comment]
@bdiette does this seem ok to you?

**Comment by bdeitte** [comment]
@gkatsev This seems fine to me.  I was going to suggest a test for this as well, and I added a simple one locally that I expected to fail (and was going to then just suggest it added in here where it should work).  But when I run "grunt test" locally on master, it passes.  And I don't see unit tests listed in the build file.  What obvious thing am I missing here?  Here's the test in any case, to add within 'test steamToParts' in test/unit/tech/flash-rtmp.test.js:
```
  parts = Flash.streamToParts('http://myurl.com/really?streaming=fun&really=fun');
  ok(parts.connection === 'http://myurl.com/');
  ok(parts.stream === 'really?streaming=fun&really=fun');
```

**Comment by bdeitte** [comment]
I realized right now that the test problem was PEBCAK.  As penance, I'll add the test here in a new PR shortly.

**Comment by gkatsev** [comment]
Thanks! Merged this manually to give credit to you both. 4e395b6b0261286f23a5cd42724a893071c2f044 and a25c4c98f3a4faea4c7db32d75f9d0907e4b8196 and 977eedda79c009bbab0b37c6e9c98b237490f8cb

**Pull request closed without merging**
