### PR TITLE
Feature/clean up player objects in tests

### PR DESCRIPTION
**Pull request by rlchung**
## Description
Fixed Issue #2895 ; cleaned up player objects in tests.
Added player.dispose() function where necessary. 

## Specific Changes proposed
N/A

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](http://jsbin.com/axedog/edit?html,output))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by BrandonOCasey** [comment]
From a quick once over in each of the files it looks like you got all the dispose calls that we were missing!
EXCELLENT

**Comment by BrandonOCasey** [comment]
also LGTM :)

**Comment by misteroneill** [comment]
Nice. LGTM. Thanks @rlchung 

Ultimately, we'll want to refactor the tests such that this can be achieved in a `afterEach` step, but this is perfect for now.

**Comment by rlchung** [comment]
@gkatsev Done!

**Comment by gkatsev** [comment]
Awesome, thanks!

**Comment by gkatsev** [comment]
Oops, forgot the # in the commit. This is closed by https://github.com/videojs/video.js/commit/af6beb21c3bb8b91b5df626e49fe29cf23f15058.

Thanks @rlchung.

**Pull request closed without merging**
