### PR TITLE
WIP: Webpackify

### PR DESCRIPTION
**Pull request by gkatsev**

### CODE REVIEW

**Comment by gkatsev** [comment]
initial assets output for the new webpack build:
```
┌──────────────┬───────────┬───────────┐
│ filename     │      size │   gzipped │
├──────────────┼───────────┼───────────┤
│ video.cjs.js │ 148.87 KB │  40.75 KB │
├──────────────┼───────────┼───────────┤
│ video.js     │  698.2 KB │ 159.45 KB │
├──────────────┼───────────┼───────────┤
│ video.min.js │ 172.26 KB │  48.47 KB │
└──────────────┴───────────┴───────────┘
```
compared to current master:
```
┌─────────────────────────────────────────────┬───────────┬───────────┐
│ filename                                    │      size │   gzipped │
├─────────────────────────────────────────────┼───────────┼───────────┤
│ video.cjs.js                                │ 630.82 KB │ 139.89 KB │
├─────────────────────────────────────────────┼───────────┼───────────┤
│ video.es.js                                 │ 630.58 KB │ 139.84 KB │
├─────────────────────────────────────────────┼───────────┼───────────┤
│ video.js                                    │ 695.03 KB │ 157.63 KB │
├─────────────────────────────────────────────┼───────────┼───────────┤
│ video.min.js                                │  188.8 KB │  49.79 KB │
└─────────────────────────────────────────────┴───────────┴───────────┘
```

Things of note:
- can't output a `video.es.js` via webpack because it doesn't have a `modules` target, only `umd`, `amd`, and `commonjs`.
- the cjs file is minimized and optimized by default thus the much smaller sizes
- the video.js file, which is unminified, is 2K larger gzipped with webpack than with rollup
- the video.min.js file is ~1K smaller than with rollup.

**Comment by gkatsev** [comment]
Though, I remembered that we haven't ran babel on the output yet, so, it might get a bit larger because of that. Hopefully, it'll stay about the same after compilation.

**Comment by gkatsev** [comment]
After adding in babel-loader, the video.min.js gzipped filesize is 59.88, which is a 20.27% increase in size.

**Comment by BrandonOCasey** [comment]
You can also include external for the `global` dependency. This is how I did it in the [other pr](https://github.com/videojs/video.js/pull/4985/files): 
```js
externals: {
  'global/window': 'window',
  'global': 'window',
  'global/document': 'document'
},
```

**Comment by gkatsev** [comment]
So, given that VHS is switching to rollup, we're going to stick with rollup for now as well. Superseded by #5057.

**Comment by axten** [comment]
I'm sad to see your decision..
I think the biggest problem using webpack is the plugin structure.
they register itself with a global available videojs and a webpack config hack is necessary:
```
new webpack.ProvidePlugin({
    'window.videojs': 'video.js',
}),
```
in my opinion, this should be fixed in es6 context in the plugins.

maybe like this api:
```
import videojs from 'video.js/dist/video.cjs';
import httpStreaming from '@videojs/http-streaming/dist/videojs-http-streaming';

import qualitySelector from 'silvermine-videojs-quality-selector';
import qualityLevels from 'videojs-contrib-quality-levels';

class Player {
    constructor() {
        
        videojs.addPlugins([
            httpStreaming,
            qualitySelector,
            qualityLevels
        ]);

        const player = videojs('player_id');
    }
}
```

do you think this is a good idea?
@gkatsev

**Comment by axten** [comment]
ok I agree that my problem is not related to webpack vs. rollup...
I tested your example and it worked without `ProvidePlugin` so I found out that I was importing the wrong file:
`import '@videojs/http-streaming';`
instead of
`import '@videojs/http-streaming/dist/videojs-http-streaming';`
fixed the error for me... 
sorry for wasting your time !

**Comment by gkatsev** [comment]
no worries.

**Pull request closed without merging**
