### PR TITLE
feat: setup Crowdin Localization

### PR DESCRIPTION
**Pull request by andrii-bodnar**
Hey everyone,

It's Andrii from Crowdin. I'm using video.js in some of my projects and I'd like to fully translate the app into the Ukrainian language.

Just did some analysis of the current i18n workflow and it feels like GitHub issues and PRs reported by the community are not so easy to handle. The community translators can work together in Crowdin, translations would be delivered as PR and volunteers can raise issues for problematic strings via Crowdin.

I'm suggesting the integration with Crowdin via GitHub Actions. Crowdin is free for open-source projects. This integration works in the following way:
- the action runs every 6 hours (actually, it's up to you what trigger to use, it could also be a push to the default branch, for example). Workflow example - [here](https://github.com/andrii-bodnar/video.js/runs/6902572500?check_suite_focus=true)
- upload new source texts to the Crowdin project
- upload existing translations to Crowdin (using the `upload_translations` action config parameter, it's necessary only for the first time)
- download all the new translations from Crowdin and commit these translations to the `localization_branch_name`
- open a Pull Request with the latest translations.

You can find my demo Crowdin project here - [videojs-demo](https://crowdin.com/project/videojs-demo) (not all the target languages are here).

Example of the first PR that will be created by Crowdin Action - https://github.com/andrii-bodnar/video.js/pull/3/ (Don't worry about the diffs - it just sorted keys according to keys order in the English file and added some missing keys with the English translations that later will be replaced with the translations made in Crowdin)

Later, you will be able to set up the [Docusaurus integration](https://docusaurus.io/docs/i18n/crowdin) for your docs also (#5144)

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
In addition, there are some great Crowdin apps to engage the community translations:
- [README.md Contributors](https://store.crowdin.com/readme-md-contributors) CLI - it allows you to automate the maintenance for your contributors' table. It can be also done via GitHub Actions.
- [Badges & Status Images](https://store.crowdin.com/bds) - allows generating badges, charts, and additional graphics for each language in your Crowdin Project.

**The next steps we can do to move further with this integration:**
- Create a [Crowdin](https://accounts.crowdin.com/register) account.
- Submit the [Open-source project setup request form](https://crowdin.com/page/open-source-project-setup-request).
- Create a new Crowdin Project:
  - As a source language select the English.
  - Fill in other target languages.
  - In the project settings enable the global Translation Memory (optional).
- Generate a new Personal Access Token in your Crowdin account settings.
- Generate a new GitHub Token (only the `repo` scope is required).
- Create the Actions secrets for your repository:
  - `CROWDIN_PERSONAL_TOKEN` - the personal access token generated in Crowdin.
  - `CROWDIN_PROJECT_ID` - ID of the Crowdin project.
  - `GH_TOKEN` - the personal access token generated in GitHub.
- merge this PR.

**Comment by mister-ben** [comment]
Interesting. The import of languages into Crowdin doesn't seem quite right in some cases - looking at the German translation, items that are present in our de.json where the translation is the same as English, like "LIVE" or "Pause", show up as a missing translation the same as strings where there is genuinely no translation yet, like "No content". 

https://crowdin.com/translate/videojs-demo/20028/en-de?filter=basic&value=0

**Comment by andrii-bodnar** [comment]
@mister-ben thanks for the fast response, let me check it

**Comment by andrii-bodnar** [comment]
Hi @mister-ben, please review the latest changes 🙂

**Pull request closed without merging**
