### PR TITLE
feat: update exposed utility functions and deprecate several top-level methods of the videojs global

### PR DESCRIPTION
**Pull request by misteroneill**
## Description
This builds on #7717 by deprecating several properties of the `videojs` global in favor of exposing utilities organized within objects. The non-deprecated utility functions APIs in Video.js 8 will be:

```
videojs.browser
videojs.dom
videojs.fn
videojs.log
videojs.num
videojs.obj
videojs.str
videojs.time
```

### Pre-existing Utility Objects
- `videojs.browser`
- `videojs.dom`
- `videojs.url`

### Newly Exposed Utility Objects/Functions
- `videojs.dom.computedStyle`
- `videojs.num`
- `videojs.obj` (excluding `assign`)
- `videojs.str`
- `videojs.time`

### `videojs` Global Deprecations
| Deprecated Method | Intended Change in 8.0 |
|---------------------|---------|
| `videojs.extend` | to be removed, use native ES6 classes instead |
| `videojs.mergeOptions` | to become `videojs.obj.merge` |
| `videojs.bind` | to be removed (though still used internally), use `Function.prototype.bind` instead |
| `videojs.createTimeRange` | to be removed, use `videojs.time.createTimeRanges` instead |
| `videojs.createTimeRanges` | to become `videojs.time.createTimeRanges` |
| `videojs.formatTime` | to become `videojs.time.formatTime` |
| `videojs.setFormatTime` | to become `videojs.time.setFormatTime` |
| `videojs.resetFormatTime` | to become `videojs.time.resetFormatTime` |
| `videojs.parseUrl` | to become `videojs.url.parseUrl` |
| `videojs.isCrossOrigin` | to become `videojs.url.isCrossOrigin` |
| `videojs.computedStyle` | to become `videojs.dom.computedStyle` |
| `videojs.defineLazyProperty` | to become `videojs.obj.defineLazyProperty` |

### Internal Code Organization Changes

Further, there are some internal code organization changes to make things better match the future:

- `utils/obj.assign` is removed as it was internal and no longer needed (along with `@babel/plugin-transform-object-assign`)
- `utils/merge-options` module/function is consolidated into `utils/obj.merge`
- `utils/computed-style` module/function is consolidated into `utils/dom.computedStyle`
- `utils/define-lazy-property` module/function is consolidated into `utils/obj.defineLazyProperty`
- `utils/format-time` and `utils/time-ranges` modules are consolidated into `utils/time` module
- `utils/clamp` is renamed to `utils/num`
- `utils/string-cases` is renamed to `utils/str`

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Change has been verified in an actual browser (Chrome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Review by mister-ben — COMMENTED** [review]
Shouldn't we add jsdoc `@deprecated` tags?

**Comment by misteroneill** [comment]
Good point! I think the JSDoc formatting will have to change to reflect this because I don't think we can include an `@deprecated` message with `@borrows`.

**Comment by misteroneill** [comment]
Good point! I also realized that we should probably implement the new API in 7.x (where new methods will exist) so code can be migrated before 8.0 is released.

**Review by mister-ben — APPROVED** [review]
Looks good, codecov seems to be exaggerating.

**Comment by gkatsev** [comment]
> codecov seems to be exaggerating

that's its favorite pastime

**Review by gkatsev — APPROVED** [review]
We'd probably want a followup PR against VHS so that it doesn't generate any deprecation warnings in the `next` branch either.

**Comment by misteroneill** [comment]
Yep, we'll need that because it uses `mergeOptions`.

**Pull request merged**
