### PR TITLE
update videojs-font

### PR DESCRIPTION
**Pull request by gkatsev**

### CODE REVIEW

**Comment by dmlap** [comment]
LGTM

**Comment by misteroneill** [comment]
LGTM

**Comment by gkatsev** [comment]
Actually, I need to add the wrapcodepoints task here as well :/

**Comment by misteroneill** [comment]
LGTM, round 2

**Comment by gkatsev** [comment]
Ok, so, I updated this PR based on https://github.com/videojs/font/pull/12

--------------
 Generate css using the codepoint-fixed sass files

The regular exported sass files will keep using the normal sass files
but users can use the new endpoint of `vjs.scss` which will use the
codepoint-fixed sass. They'll also need to manually wrap the codepoints
on their generated css file after the fact.

**Comment by gkatsev** [comment]
The reason tests are failing is because it depends on videojs/font#12 to be merged and released.

**Comment by misteroneill** [comment]
LGTM, third time's a charm!

**Pull request closed without merging**
