### PR TITLE
update reportUserActivity

### PR DESCRIPTION
**Pull request by cucygh**
## Description
Please describe the change as necessary.
If it's a feature or enhancement please be as detailed as possible.
If it's a bug fix, please link the issue that it fixes or describe the bug in as much detail.

## Specific Changes proposed
Please list the specific changes involved in this pull request.

## Requirements Checklist
- [ ] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](http://jsbin.com/axedog/edit?html,output))
- [ ] Reviewed by Two Core Contributors

pass event to handleActivity and then we can use it in reportUserActivity method

### CODE REVIEW

**Comment by gkatsev** [comment]
Thanks for the PR; however, I'm not sure we actually need this change. `reportUserActivity` just sets a boolean and is already called in several places without any arguments. I think what we actually want is removing `event` from it's method signature as it is never used.

**Comment by cucygh** [comment]
yeah,In fact, it is necessary for example different business use the same player and we need get all user‘s interaction such as ’click‘，if pass event arguments to reportUserActivity then we can make a plugin to override the API for different implementation of user interaction collecting without the player change

**Comment by gkatsev** [comment]
I'm not really seeing the usecase and I cannot recommend [overriding that method](https://www.nczonline.net/blog/2010/03/02/maintainable-javascript-dont-modify-objects-you-down-own/).

Are the `useractive` and `userinactive` events not enough?

I'm going to close this PR for now. But please reply with your usecase and we can talk about whether it's something we want to support or not or maybe there's a better way of doing what you want to do. The PR can always be re-opened later if we feel like we want to bring it in.

**Comment by cucygh** [comment]
the usecase is I'd like to know how much times the playButton is clicked,how much the VolumeSlide is cliked and how much times otherButton is clicked,at last send the info to server.

i see the code about useractive,it's simply true or false,i can't get the element directly and the handleUserActive_ method isn't a implementation

**Pull request closed without merging**
