### PR TITLE
Set the 'lang' attribute on text track display elements, if the language of the track is known

### LINKED ISSUE #7487: The language of text track's cues is not marked programmatically when they are displayed
## Description
WCAG 2.0/2.1 [Success Criterion 3.1.2 Language of Parts](https://www.w3.org/TR/WCAG21/#language-of-parts) requires that "The human language of each passage or phrase in the content can be programmatically determined ...".

Text tracks (captions, subtitles, and descriptions) may be in any language, and in particular, they may be in a different language from the rest of the content of the page in which they are displayed. Therefore, the text track may not be in the language indicated by the `lang` attribute of the HTML page, or [the `lang` attribute of the player](https://github.com/videojs/video.js/blob/main/src/js/player.js#L804).

Text tracks have a `srclang` attribute which, if present, indicates the language of the text track; this language attribute should be applied as a `lang` attribute either on the whole region that displays the track's cues or on each cue that is displayed.

Specifically, at https://github.com/videojs/video.js/blob/main/src/js/tracks/text-track-display.js#L421, a CSS style is applied to each text track display element according to the track's language; this could also be used to set the `lang` attribute of that element.

## Steps to reproduce
1. Go to https://videojs.com/advanced?video=elephantsdreammp4
2. Play the video
3. Select one of the CC tracks which is not English (e.g. Russian)
4. Pause the video when a caption is being displayed
4. Examine the DOM, and notice that neither the `<div class="vjs-text-track-display" ...>` nor any of its child elements have a `lang` attribute set, although the language has been applied in a CSS class, e.g. `<div class="vjs-text-track-cue vjs-text-track-cue-ru" ...>`

### PR DESCRIPTION
**Pull request by OwenEdwards**
## Description
Fixes #7487 

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [x] Change has been verified in an actual browser (Chrome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Review by gkatsev — APPROVED** [review]

**Review by gkatsev — APPROVED** [review]

**Comment by OwenEdwards** [comment]
I wish I knew how to add a test for this change, in part so that it doesn't make the code coverage (fractionally) worse, but I don't! Does anyone want to add a test to this?

**Comment by gkatsev** [comment]
@OwenEdwards got some tests for this here https://github.com/OwenEdwards/video.js/pull/3

**Comment by mister-ben** [comment]
This also fixes this problem I didn't realise we have that Chinese glyphs could be used incorrectly with Japanese subs, if the player language isn't Japanese.

https://heistak.github.io/your-code-displays-japanese-wrong/

**Comment by gkatsev** [comment]
lol, not sure why CI doesn't want to re-run stuff. Maybe I should've made the PR from my fork instead.

**Review by gkatsev — APPROVED** [review]

**Comment by gkatsev** [comment]
The code coverage went a tiny bit up.

**Pull request merged**
