### PR TITLE
refactor: Remove logic and style that accommodates non-flex fallbacks

### PR DESCRIPTION
**Pull request by roman-bc-dev**
## Description
Remove logic that checks for browser flexbox feature support and any style rules that specifically target the `.vjs-no-flex` class. We are assuming standard flex support for Video.js 8 and onward.

## Specific Changes proposed
- Remove `flexNotSupported_()` and associated call.
- Remove specific style rules that target the `.vjs-no-flex` class added by the `flexNotSupported_()`method. Consolidate css rule groups where `.vjs-no-flex` targeting was removed.

## Requirements Checklist
- [ ] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Change has been verified in an actual browser (Chrome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Review by alex-barstow — APPROVED** [review]
LGTM

**Comment by gjanblaszczyk** [comment]
Hi Roman,
In your description you wrote, "We are assuming standard flex support for Video.js 8 and onward.". However, you want to merge this PR into "main" branch. I guess you should push it into "next" branch instead. 
Apart from that, the code looks good to me.

**Comment by roman-bc-dev** [comment]
Good catch @gjanblaszczyk!

The path of least resistance here (switching the base branch), means we're including changes from the 7.20.1 patch into next (since main is ahead by a few commits). I'm assuming we would have done that eventually anyway but just want to check if that's above board to include those changes here.

**Comment by gkatsev** [comment]
yeah, we do need to cherry-pick the changes from main into `next` at some point.

@roman-bc-dev if you're able to squash your two commits into a single commit, we can use the "rebase and merge" functionality to bring all the commits from this PR into `next`. Otherwise, we'll want to bring the commits from `main` separately and then rebase this PR against `next`.

**Comment by roman-bc-dev** [comment]
For whatever reason, the usual git trickery wasn't working on my local branch. So to save some time and effort, I created a new branch off of `next` and fresh PR here: https://github.com/videojs/video.js/pull/7820

**Pull request closed without merging**
