### PR TITLE
fix: don't let the player be translated except captions

### PR DESCRIPTION
**Pull request by gkatsev**
This is another follow-up to #6699.

Potentially, it means we could get rid of #6977

### CODE REVIEW

**Comment by gkatsev** [comment]
@OwenEdwards yeah, I was thinking the scenario of only Spanish captions without English captions. Theoretically, English->English in that case would be a no-op.
https://github.com/videojs/video.js/pull/7493 makes sense to have.

The items in the text track menu won't get translated because they're covered by the main `translate=no`.

**Comment by OwenEdwards** [comment]
@gkatsev you wrote:
> The items in the text track menu won't get translated because they're covered by the main `translate=no`.

Wouldn't it make sense to put `translate="yes"` on those items, and on the content of the Captions Settings dialog?

Broadly, I understand the #6699 identifies a specific case where using Google Translate to translate a page that includes video.js causes a problem, and applying `translate="no"` to the whole player is a quick fix. Longer-term, could we be more targeted about what gets translated and what doesn't?

**Comment by gkatsev** [comment]
> Wouldn't it make sense to put `translate="yes"` on those items, and on the content of the Captions Settings dialog?

Maybe, if we can get just the text isolated enough. Since, we wouldn't want to introduce issues where translate replaces the elements and using the menu doesn't work anymore.

Yup, applying `translate=no` to the entire player is definitely the quicker fix, and we can definitely enable more elements to be available as `translate=yes`, though, I think time is better spent on making our translation support better and more usable so that people don't need to go through this translation thing.

If there's no objections with proceeding with this PR, I'd like to merge it in.

**Comment by gkatsev** [comment]
Also, I guess the alternative is to only do `translate=no` on the player right now and then audit the player to see where we can/should do `translate=yes`

**Comment by OwenEdwards** [comment]
LGTM.

**Comment by Zyhazeeb** [comment]
Hi friends

**Pull request merged**
