### PR TITLE
Set cache before 'mouseenter' event for inactivityTimeout

### PR DESCRIPTION
**Pull request by iosamuel**
## Description
We need to define the cache for `inactivityTImeouot` before the `mouseenter` event, because if you do play on the `controlBar` for example and go out, the actual `mouseenter` event of it never gets triggerd, and so the cache is gonna be always undefined. 

It's a really visible bug when you have a custom player with the control-bar all the way bottom (-40px) and you set a `inactivityTimeout: 0`, it gets overriden by the undefined and gets hidden always.

### CODE REVIEW

**Comment by misteroneill** [comment]
> if you do play on the `controlBar` for example and go out, the actual `mouseenter` event of it never gets triggerd

This definitely sounds like a bug, but perhaps the bug is that the `mouseenter` event is being obscured by something?

**Comment by gkatsev** [comment]
Can you elaborate on what you mean by 
> because if you do play on the `controlBar` for example and go out

Though, this change seems fine to me regardless, it makes sense to prime it with a default value. Though, it should potentially be done in the [resetCache_ method.](https://github.com/videojs/video.js/blob/master/src/js/player.js#L2053-L2061)

**Comment by iosamuel** [comment]
@misteroneill No, the `mouseenter` is not obscured, it's just that the whole part of user activity is being initialized in the `play` event: https://github.com/videojs/video.js/blob/46d2d494feaf204931721d5eb4dda17e67ac369c/src/js/player.js#L522

**Comment by iosamuel** [comment]
@gkatsev As I said to @misteroneill, since the userActivity events such as `mouseenter` are being listened only when you hit play, if you are over the `controlBar` to hit play (`playButton`), you actually are never gonna fire the `mouseenter` event which sets the cache for `inactivityTimeout` until you go out of the player and come back again with your cursor.

I will definitely check on the resetCache_ method to make it better. Thanks!

**Comment by gkatsev** [comment]
Oh, I see. Thanks.

**Comment by gkatsev** [comment]
This probably wasn't noticed because we don't have the control bar showing by default.

**Comment by iosamuel** [comment]
Yes, exactly, as I made some custom video-players, one of them have a skin that always shows the control bar (or at least it tries haha).

**Comment by iosamuel** [comment]
@gkatsev The `resetCache_` worked like a charm! I updated the PR.

**Pull request merged**
