### PR TITLE
Change "video" to "media" in error messages.

### LINKED ISSUE #2407: Make errors more generic. It won't always be "video"
If an error occurs while trying to play an audio file, I still get the generic "The video could not be loaded, either because the server or network failed or because the format is not supported." error message. Since video.js can play audio files as well, "video" should be changed to "media" or similar.

### PR DESCRIPTION
**Pull request by sirlancelot**
Fixes #2407

### CODE REVIEW

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 08ae1cd0ea86c04285319ec283c8bc62f124add8
Build details: https://travis-ci.org/pam/video.js/builds/72629754

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by sirlancelot** [comment]
Looks like the failed test has nothing to do with this change in particular: [Build Log Line 566](https://travis-ci.org/pam/video.js/builds/72629754#L566)

**Comment by gkatsev** [comment]
@pam retry

**Comment by gkatsev** [comment]
Yep, test failure is saucelabs being flaky

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 08ae1cd0ea86c04285319ec283c8bc62f124add8
Build details: https://travis-ci.org/pam/video.js/builds/72633146

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by mister-ben** [comment]
All of the files in lang would also need to be updated. They use the English error as keys.

**Comment by heff** [comment]
We should probably just pull this in and let the translations come in as they can. We could go back and ping the original translators too.

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 9eab598bde173aa1867465a34c2266d24f049a1d
Build details: https://travis-ci.org/pam/video.js/builds/72733512

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by dmlap** [comment]
@heff I believe mister-ben is pointing out that the translations won't work *at all* because the English keys won't match. It makes sense to let the values get updated independently but are you sure we should pull this in without updating the keys in the translations?

**Comment by gkatsev** [comment]
All the keys were updated in the language files.

**Comment by sirlancelot** [comment]
I updated the keys in 9eab598 as seen right above @pam's comment.

**Comment by sirlancelot** [comment]
I updated the keys in 9eab598 as seen right above @pam's comment. Unfortunately, I don't speak the 25 languages to update their values ;)

**Comment by dmlap** [comment]
Oops. That's what I get for trying to do a code review from my phone. Nevermind my comment. LGTM.

**Pull request closed without merging**
