### PR TITLE
Allow customizing the port used by grunt connect

### PR DESCRIPTION
**Pull request by misteroneill**
Does what it says on the box.

### CODE REVIEW

**Comment by misteroneill** [comment]
For some reasoning here, it was getting tedious to switch between `stable` and `master`, so I have a second clone now. This allows both to run `grunt connect` simultaneously.

**Comment by gkatsev** [comment]
I think connect also has an option to try and figure out the next open port. Could we enable that option as well?

**Comment by gkatsev** [comment]
https://github.com/gruntjs/grunt-contrib-connect#useavailableport

**Comment by misteroneill** [comment]
I suppose that works, too. Why not both?

**Comment by gkatsev** [comment]
Yep, both is what I meant :)

**Comment by heff** [comment]
lgtm!

**Pull request closed without merging**
