### PR TITLE
fix(MenuButton) Unify behavior of showing/hiding

### PR DESCRIPTION
**Pull request by justinanastos**
Same as https://github.com/videojs/video.js/pull/3993 but targeting `master`.

### CODE REVIEW

**Comment by gkatsev** [comment]
Thanks @justinanastos. Can you update the [subs-caps-button](https://github.com/videojs/video.js/blob/master/src/js/control-bar/text-track-controls/subs-caps-button.js) as well? It was just added and should work similar to the captions-button.

**Comment by justinanastos** [comment]
@gkatsev I'm sorry, I totally forgot to update the `sub-caps-button`!

**Comment by justinanastos** [comment]
Wew, I've attained `Contributor` status!

https://cl.ly/0d0p0F1q451p/Image%202017-03-07%20at%2011.36.17%20AM.png

**Comment by gkatsev** [comment]
@justinanastos no worries. I have a PR coming up that rectifies it.
Also, \o/

**Comment by gkatsev** [comment]
Here's my update #4171.

**Pull request merged**
