### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by atefBB**
fix typos & propose changes.

### CODE REVIEW

**Comment by mister-ben** [comment]
Thanks. If you've time there are many more strings with no Arabic translations at all. See the `en.json` template and the docs/translations-needed.md doc for which.

**Comment by atefBB** [comment]
Great! I'll check them soon In Shaa Allah !

**Comment by gkatsev** [comment]
I'm going to pull this in. Would be awesome if you can help provide the other translations @atefBB!

**Comment by atefBB** [comment]
@gkatsev Thx! I'll do when I have time.

**Pull request merged**
