### PR TITLE
Arbitrary change to test Savage

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 6e25cfb725ecdd6bce6eb79e8b710467b11968c7
Build details: https://travis-ci.org/pam/video.js/builds/62322453

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
Huzzah!

**Comment by mmcc** [comment]
@pam retry

**Comment by pam** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 6e25cfb725ecdd6bce6eb79e8b710467b11968c7
Build details: https://travis-ci.org/pam/video.js/builds/62323004

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by mmcc** [comment]
HUZZAH :trumpet: :party: :+1:

**Comment by heff** [comment]
Wow, so very cool. :+1:

**Pull request closed without merging**
