### PR TITLE
Text track button does not hide after remove tracks

### PR DESCRIPTION
**Pull request by mctep**
Hello! I write own tech that supports text tracks. How to clear text tracks, after load next source in player?

I try to remove **text** (upd) tracks like below:

```js
const tracks = player.textTracks();
tracks.tracks_.forEach(track => tracks.removeTrack_(track));
```

But `TextTrackButton` push OFF `item` for disabling any text tracks and return items with single element.

For the first displaying component it is work because in constructor of `TrackButton` it hides when length of items less than 2:

```js
if (this.items.length <= 1) {
  this.hide();
}
```

But when `TextTracks` updates in `MenuButton` it hides only when length of items is 0:

```js
if (this.items && this.items.length === 0) {
  this.hide();
} else if (this.items && this.items.length > 1) {
  this.show();
}
```

So I think it would better that `TextTrackButton` should return empty array of items if there are no tracks in player. This PR is just example solution.

### CODE REVIEW

**Comment by gkatsev** [comment]
Your way of removing tracks isn't our recommended method for this. What about doing something like the following instead?
```js
// only remote tracks are actually removable
const tracks = player.remoteTextTracks();

let i = 0;
while (i--) {
  player.removeRemoteTextTrack(tracks[i]);
}
```

**Comment by mctep** [comment]
Thank you. I will use only remote text tracks.
However it does not fix problem with hiding `TextTrackButton` after removing all text tracks.

**Comment by gkatsev** [comment]
Trying it out locally, the button is removed for me. Do you have a [reduced test case](https://css-tricks.com/reduced-test-cases/)?

**Comment by misteroneill** [comment]
I have confirmed that removing a remote text track removes the CC button when using video.js 5.12.

Here is a [reduced test case](http://output.jsbin.com/tisube).

**Comment by gkatsev** [comment]
Thanks for confirming @misteroneill. Based on that, I don't think this PR is necessary. If you're seeing an issue with the button being removed, could you open an issue with a reduced test case?

Thanks.

**Comment by mctep** [comment]
Hm. Thank you. I will look into it more.

**Comment by mctep** [comment]
Oh. This issue actual for subtitles tracks and `SubtitlesButton`. Not for captions. There is threshold In `CaptionsButton`.

Here is modified your [reduced test case](http://jsbin.com/cepiyisezo)

**Comment by gkatsev** [comment]
Hm... Sounds like we want to move the threshold piece of code from captionsButton to the TextTrackButton since I think that descriptions tracks would have the same issue now as well.

**Comment by gkatsev** [comment]
Can you open an issue with this? If you want to attemp that solution, that would be awesome as well. Thanks for bringing this to our attention @mctep.

**Pull request closed without merging**
