### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by mmcc** [comment]
Thanks! Any reason there are 2 PRs to update the same file?

**Comment by paladox** [comment]
Because if I update multiple in one patch it slows it down  but if I do it in multiple patches only one patch is slowed if the change is breaking or going to cause problems.

**Comment by gkatsev** [comment]
Merging, thanks. In the future, it would be helpful if the name of the PR was more meaningful to the contents.

**Comment by paladox** [comment]
Thanks and sorry.

**Comment by gkatsev** [comment]
No worries.

**Pull request closed without merging**
