### PR TITLE
Set the duration display on 'ready'

### PR DESCRIPTION
**Pull request by bc-bbay**

### CODE REVIEW

**Comment by heff** [comment]
Thanks Brandon, any more background on this one? Does it need to go out as a patch? We're trying to be relatively conservative with how much we patch 4.x because it slows down the 5.0 development.

**Comment by heff** [comment]
Code wise this looks good to me.

**Comment by cvrebert** [comment]
Don't know what happened with the Savage test here. Hopefully the logs would be enlightening.

**Comment by heff** [comment]
Is it just stalled? @mmcc could you check it out?

**Comment by bc-bbay** [comment]
Using loadedmetadata as @heff suggested works just as well as using the ready event.

I believe there is a customer waiting on this issue, so it should likely be patched. I'll submit another PR to bring it into master as well once we make a decision about whether this should be patched or not.

**Comment by dmlap** [comment]
@bc-bbay is there an equivalent patch against master for this issue? Can you link it here?

**Comment by bclwhitaker** [comment]
#2150

**Comment by bc-bbay** [comment]
No, #2150 was a mistake. I was waiting until we had the ok on this one before I duplicated the work in master, so I didn't have to make edits in two branches.

I'll create that now.

**Comment by bc-bbay** [comment]
#2169

**Pull request closed without merging**
