### PR TITLE
tsml should not be called like a function

### PR DESCRIPTION
**Pull request by misteroneill**

### CODE REVIEW

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 84483821acf9a94bad07561eb26fc6402116da08
Build details: https://travis-ci.org/pam/video.js/builds/81619395

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by forbesjo** [comment]
@pam retry?

**Comment by gkatsev** [comment]
@pam retry

LGTM

**Comment by pam** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 38751ec68f654052f1ec8ac8d711728aa07ac7b4
Build details: https://travis-ci.org/pam/video.js/builds/82161374

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by misteroneill** [comment]
:clap:

**Pull request closed without merging**
