### PR TITLE
Switched player.tech to tech_, to promote it as private

### LINKED ISSUE #2060: Make player.tech a private property
player.tech should have always been a private property, but now that we're not mangling vars it's especially important to call that out.

Just want to make sure this happens for 5.0.

### PR DESCRIPTION
**Pull request by heff**
closes #2060

Just changes player.tech to player.tech_ wherever it's used, because it's important to promote that the tech is a private reference that plugin authors shouldn't be using. This was mangled in 4.x, so should be ok to change.

### CODE REVIEW

**Comment by gkatsev** [comment]
Sounds good to me.

**Comment by moay** [comment]
Just one question concerning this. How do I access a "non standard" tech function in a component with the tech being private?

I want to access a function of a custom tech which is not a default function like `volume()` or `src()`. I built a component which can access the player internally like this: `this.player_`, but if I try to access the function like this: `this.player_.myFunction()` it doesn't work. Neither does `this.player_.tech.myFunction()` (still on rc82). 

How to eiter publish the function from within the tech or to access the function via some other way from the component?

Thanks. :-)

**Comment by heff** [comment]
How are you adding a function to the player so that
this.player_.myFunction() isn't working? That should work, and is ok to do
because it's a private var of `this`.

If you have a specific feature you want to access on a tech, you should
submit and issue about it so we can find a way to make it work the same
across all techs the same way. If we start adding tech-specific functions,
it breaks the model where any plugin can work with any tech.

**Comment by moay** [comment]
Here is the basic tech (**very** reduced) setup:

```javascript
(function() {
    var Tech = videojs.getComponent('Tech');
    var MyTech = videojs.extends(Tech, {
        myFunction: function(){
            return something;
        }
    });
    videojs.registerComponent('MyTech', MyTech);
})();
```

Now in my Component (simple button, ES6), I can't access this function via `this.player().myFunction()`. In rc82, I can do `this.player().tech.myFunction()`, but if I get the purpose of the tech being made private, this is not how it's supposed to be used. Maybe I'm just not clever enough... ;-) Is there some other way to publish a method from the tech?

**Comment by gkatsev** [comment]
In 5.0, the tech no longer has a reference to the player. But the player should still have `tech_` available. And just because it's private and discourage to use, doesn't mean that you shouldn't necessarily use it. It depends on the particular usecase.
Also, for [contrib-hls](/videojs/videojs-contrib-hls) we ended up adding a reference to the player with the name of the tech for us to use. `player.hls` would reference the hls tech. Though, we're transitioning away from a tech for it and to source handlers.

**Comment by moay** [comment]
Okay, thanks. :)

**Comment by heff** [comment]
Please don't use tech_ until you've at least submitted an issue about why you needed to use it and what the player is lacking. I haven't seen a usecase yet where we shouldn't be looking into how to expose the information at the player level, in a way that's consistent between techs (even if it's just reporting that the info/feature isn't supported).

The consistency between techs is actually growing in importance for video.js users (and users of video.js plugins), so we need to keep being religious about that.

**Comment by mmcc** [comment]
lgtm

**Pull request closed without merging**
