### PR TITLE
Fixed Issue-5557

### PR DESCRIPTION
**Pull request by joaomalheiro**
## Description
Provides a better solution to issue #5557. Instead of removing the background on the CSS file the focus is now attributed to menu-item that is currently selected. 
@gkatsev 

## Specific Changes proposed
Added a function that sets the focus of the menu to the item that is currently selected after receiving the click event.

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [x] Change has been verified in an actual browser (Chome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by BrandonOCasey** [comment]
Seems like this pull request is currently failing due to linting errors. Can you run `npm run lint -- --errors` and fix the errors that are reported?

**Comment by joaomalheiro** [comment]
I fixed the lint errors in the last commit.
@gkatsev The issue had been fixed by hiding the focus with css, we provided a fix that would actually focus only on the selected and move with the keyboard arrows. We know it was already closed but we are working on a class project on which we had to fix an issue and we chose this one before it was closed so we decided to provide a different solution.

**Comment by gkatsev** [comment]
Ah, I see. To me this seems like it hides the problem rather than fixes it. The issue is about the different expectations of mouse and non-mouse users. A mouse user wouldn't expect focus styles to show up where non-mouse users would and need. The current fixes uses the focus-visible selector (or polyfill) to hide the style for mouse users.
By focusing the currently selected option, to me it seems like hiding the issue as the focus styles wouldn't be noticeable compared to the selected styles.

**Comment by gkatsev** [comment]
However, whether we should focus the selected option is actually a good question that is not related to issue #5557. Any thoughts on that @OwenEdwards?

**Comment by OwenEdwards** [comment]
Focusing the currently-selected menu item seems nice, but is not the expected behavior for a menu. It will confuse screen reader users.

**Comment by gkatsev** [comment]
Thanks @OwenEdwards, that's good to know.
Unfortunately, this means we can't accept this contribution as it would violate user expectations. Thanks for making the PR and having a conversation with us, though.

**Pull request closed without merging**
