### PR TITLE
Add an Audio Description icon to an audio track name in the track menu if it is "main-desc" kind.

### PR DESCRIPTION
**Pull request by OwenEdwards**
## Description
Indicate in the Audio Tracks menu if an audio track contains Audio Description.

## Specific Changes proposed
Add an icon after Audio Description audio tracks in the audio tracks menu, in the same way that the `subs-caps` menu adds an icon after either captions or subtitles tracks.

Note that [videojs-contrib-hls](https://github.com/videojs/videojs-contrib-hls ) added support for [indicating that an audio track contains Audio Description](https://github.com/videojs/videojs-contrib-hls/commit/bfa1fbfe1d5e20d24ebd0f18ffbabe7b5bcea9bd) (by setting its `kind` to `main-desc`) in v5.4.0.

## Requirements Checklist
- [ ] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Change has been verified in an actual browser (Chome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](http://jsbin.com/axedog/edit?html,output))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by OwenEdwards** [comment]
@gkatsev @mister-ben can you take a look at this - the additional icon in the audio menu is causing the menu to have scrollbars or the icon gets clipped:



I can't figure out how to avoid that. Any thoughts?

**Comment by mister-ben** [comment]
I haven't dug into this yet but this is a problem for the subs/caps menu too - it's just the labels are generally short enough that I hadn't noticed.

**Comment by gkatsev** [comment]
We probably want to truncate the text if there's an icon and set the `title` attribute to the fulltext, so, visually it'll be truncated, but will be available to screen readers or on hover.

**Comment by OwenEdwards** [comment]
Another alternative would be to move Audio Description text tracks into a menu which contains those tracks *and* subtitles and captions, like Safari does:

**Comment by prozak915** [comment]
Thx guys iam relally aproshieitet fot your help u save my life a havenr sklep for 2 data i on tnie phone its really słów to do everything

**Comment by misteroneill** [comment]
Was there ever a solution for the overflow issue?

**Comment by OwenEdwards** [comment]
@misteroneill yes, the "Change CSS based on PR #5228 to fix menu layout with icons" pulls in the solution from that PR which means the AD icon wraps to the next line if necessary.

**Pull request merged**
