### PR TITLE
Fix 3140

### PR DESCRIPTION
**Pull request by seescode**
This fixes 3140 where control bar hides certain elements prematurely in IE.

### CODE REVIEW

**Comment by gkatsev** [comment]
Does this make sass not turn the string into a utf8 character? If so, I wonder if we could do the same thing for our font and then we could get rid of the "wrapcodepoints" grunt script.

**Comment by seescode** [comment]
image

It just outputs \0screen in the generated dist/video-js.css

**Comment by gkatsev** [comment]
Cool, that's what we want to happen.

**Comment by gkatsev** [comment]
Awesome, LGTM.

**Comment by misteroneill** [comment]
LGTM

**Pull request closed without merging**
