### PR TITLE
fix warning - element supplied is not included in the DOM

### PR DESCRIPTION
**Pull request by KevinBrogan**
Videojs currently relies on the document object from the window that videojs script is instantiated in, in order to determine if the element it will use for initialization is attached to the dom. The method used to determine dom attachment is incorrect. This fixes that method.

## Description
Please describe the change as necessary.
If it's a feature or enhancement please be as detailed as possible.
If it's a bug fix, please link the issue that it fixes or describe the bug in as much detail.

## Specific Changes proposed
document.contains(el) will only check if el is contained within that one document. This causes problems for elements in iframes.

Instead, use the element's ownerdocument instead of the global document. Additionally, check that the document in question has a default view. If the document is no longer attached to the dom, the defaultView of the document will be null.

## Requirements Checklist
- [X ] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Change has been verified in an actual browser (Chome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by thijstriemstra** [comment]
I would include all, or a summary of that info in a code comment

> document.contains(el) will only check if el is contained within that one document. This causes problems for elements in iframes.

> Instead, use the element's ownerdocument instead of the global document. Additionally, check that the document in question has a default view. If the document is no longer attached to the dom, the defaultView of the document will be null.

**Comment by KevinBrogan** [comment]
Not a bad suggestion

**Comment by thijstriemstra** [comment]
> Not a bad suggestion

And ideally, you'd also include a test for this (showing how it behaves in an iframe), but I guess it's better to wait for some confirmation from devs first.

**Comment by gkatsev** [comment]
Thanks!

**Comment by gkatsev** [comment]
FYI, https://github.com/videojs/video.js/pull/5872

**Pull request merged**
