### PR TITLE
test: add project and build names to browserstack

### PR DESCRIPTION
**Pull request by gkatsev**
videojs/http-streaming is starting to run tests in browserstack so we should name our runs better.

### CODE REVIEW

**Comment by gkatsev** [comment]
Looks like 
screen shot 2018-01-25 at 18 23 09

Previously it would just say `7907`

**Comment by forbesjo** [comment]
This might be out of the original scope of the PR but you could also turn off `video` to disable video capture and, I think, speed up VM startup. The recorded video isn't particularly useful since none of the tests have a visual output.

**Comment by gkatsev** [comment]
Turning it off sounds good to me, though, we do have the qunit output enabled and it has been helpful for IE8 debugging, but we can always add it in manually when needed and re-run the build.

**Comment by gkatsev** [comment]
Looks like turning it off doesn't really make much of a difference in our build times so I'm going to leave them on.

**Pull request merged**
