### PR TITLE
Load plugins before controls

### PR DESCRIPTION
**Pull request by bc-bbay**
For issue #1980

### CODE REVIEW

**Comment by heff** [comment]
Awesome, thanks @bc-bbay. @carpasse want to take a look at this one?

I'm wondering if we should init plugins after the player element is created but before children are added.

**Comment by mmcc** [comment]
Just a note, we definitely need to document that current plugins will need to wait for the `ready` event in order to see the same behavior they do today.

**Comment by heff** [comment]
@bc-bbay, could we move it to between the el and the children? I think that makes more sense.
```
this.el_ = this.createEl();
// here
this.initChildren();
```

**Comment by carpasse** [comment]
@heff and @bc-bbay that is exactly I proposed. It looks great.
Thanks

**Comment by bc-bbay** [comment]
Made a new PR (accidentally pushed this change to my fork's master, and it was trying to sneak its way into other branches) with the relocated change.

**Pull request closed without merging**
