### PR TITLE
Added keycode package and wrapper function to keyboard events handling

### PR DESCRIPTION
**Pull request by tiagofragoso**
## Description
Fixes issue videojs/video.js#3022 
Now using keycode package and wrapper function instead of 'event.which' checks for keyboard events handling

## Specific Changes proposed
Added keycode package to improve keyboard handling
Created a wrapper function at src/js/utils/keyboard-handler.js which allows for a simpler syntax when calling a sequence of key comparisons by allowing an array parameter containing key names

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [x] Change has been verified in an actual browser (Chome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by gkatsev** [comment]
Thanks, we do have a PR that already does the switch (https://github.com/videojs/video.js/pull/5571), @OwenEdwards what are your thoughts about this change in comparison to yours?

**Comment by gkatsev** [comment]
Sounds good. I can help fixup merge conflicts and what not as well.

**Comment by miguelpduarte** [comment]
@gkatsev We did not add or update any unit tests since there is no validation being performed on the key events in the components. Would it be relevant to add an issue for the creation of these kinds of tests? (Verifying if pressing a certain key triggers a certain action in a "registered" component)

**Comment by gkatsev** [comment]
I don't think tests for this specifically are necessary. Theoretically, existing tests should cover it. Also, a manual testing pass helps.

**Comment by OwenEdwards** [comment]
@tiagofragoso can you review this now that #5571 has been merged? Is there anything that that PR missed?

**Comment by OwenEdwards** [comment]
@gkatsev I'm going to recommend we close this PR. I've reviewed the changes, and although the `eventMatchesKeys` is a nice touch, it doesn't add anything functionally to the changes in #5571, and it would be non-trivial to resolve the conflicts.

**Comment by gkatsev** [comment]
Yeah, might be easier to just make a new PR with just the eventMatchesKeys method. @tiagofragoso would you be interested in doing so? Please submit a new PR then. And let me know if you need help.

Anyway, going to close this PR for now.

**Pull request closed without merging**
