### PR TITLE
bower.json fixes

### PR DESCRIPTION
**Pull request by cvrebert**
Per https://github.com/bower/bower.json-spec/commit/a325da3d79baab018c572d75dc1781b12322f6cd

### CODE REVIEW

**Comment by heff** [comment]
Ah, makes sense, thanks! We'll need to remove the bower.json from the grunt version update task too.

**Comment by mmcc** [comment]
@cvrebert I realized after merging #2145 that `bower.json` doesn't match our new naming in dist. Mind updating this PR to fix that as well? 

It should just be `dist/video.js` and `dist/video-js.css` for the entry points.

**Comment by cvrebert** [comment]
There are some additional complications, but this should now fix `main`.

**Comment by heff** [comment]
Thanks!

**Comment by cvrebert** [comment]
@heff And rebased again to merge cleanly. Please merge soon, as every version number bump you guys do causes a fresh merge conflict.

**Comment by heff** [comment]
heh, was just working on that

**Comment by heff** [comment]
Merged! Thanks.

**Pull request closed without merging**
