### PR TITLE
Add sync option to ready()

### LINKED ISSUE #2326: Setting the src is not synchronous
Even when the tech is ready, setting the source doesn't take effect at the tech level for one tick because it's [wrapped in a call to ready()](https://github.com/videojs/video.js/blob/26a78627f1f231dbbe0fa1f7441bfc1b27893be5/src/js/player.js#L1521)

### PR DESCRIPTION
**Pull request by heff**
Should fix #2326

### CODE REVIEW

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 44a6d8d8c4a48ec06688a5f61eab9ab178bdfa51
Build details: https://travis-ci.org/pam/video.js/builds/72042662

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by dmlap** [comment]
Nice. How did you look for `ready()` calls that needed to be converted to the sync form?

**Comment by heff** [comment]
`ready\([^\)]`

I only added sync for the ones that needed it or seemed like they would be better with it.

**Comment by heff** [comment]
Sorry, that could be more detailed. There were obvious ones where we were just waiting to send the call because the tech wasn't ready, but ideally they'd be synchronous. Then I also added sync to the ones that seemed like they could be player loading speed related. Otherwise if they looked like just needed to happen some time after the ready event, I left them alone.

**Pull request closed without merging**
