### PR TITLE
Fixing some unremoved event handlers and hidden video tag for html5 tech

### PR DESCRIPTION
**Pull request by giakas**
issue 1: when Tech change to html5, video is hidden.
issue2: MediaController in videojs was not releasing some handlers during dispose.
issue3: Turn off Tracking simulated progress and timeupdates when Error occured

### CODE REVIEW

**Comment by mmcc** [comment]
Thanks for the PR! Your tests aren't running at all because of the JSHint errors, but once they do, I think you're going to have more failures due to the `activateControls` changes. If you notice, that's actually defined within the scope of that function and not added to the `MediaTechController` prototype.

**Comment by giakas** [comment]
Thanks Matthew,

Fixed the JSHint errors.
And ran grunt test and got no failures.

And the activateControls, I did create a new prototype method in MediaTechController so that it can be accessible in the media.js.

Do I need to create a new pull request,, or can I update the current pull request with the new commit to fix JShint erros.

Girish.

**Comment by mmcc** [comment]
@giakas sorry for the delay, looks like the tests are passing fine now! This needs an actual review  beyond my initial, quick glance, so we'll ping this thread in the next few days.

**Comment by ange007** [comment]
It is the best PR lately, solved at last problems which were often discussed here.

**Comment by heff** [comment]
This was fixed by #2053 and the new Tech 2.0 work.

**Pull request closed without merging**
