### PR TITLE
Added watchify task

### PR DESCRIPTION
**Pull request by eXon**
If I don't get a watchify task to work I'll start punching people in the face. Seriously, we need it to stay sane or we have to wait 30 secs everytime we want to just console.log something.

### CODE REVIEW

**Comment by gkatsev** [comment]
I think it'll be better to use `grunt-browserify` that we already use to set up the watchify tasks.

**Comment by gkatsev** [comment]
But yes, we definitely need watchify.

**Comment by eXon** [comment]
@gkatsev We need to use browserify directly if we want to do that instead of grunt-browserify. I don't think it's a big deal to duplicate the options considering it doesn't work the same way. If you have an example on how to use watchify within grunt-browserify let me know.

**Comment by gkatsev** [comment]
You only need to duplicate the regular grunt-browserify config and add the [`watch`](https://github.com/jmreidy/grunt-browserify#watch) option for it to use watchify. Let me know if that works.

**Comment by eXon** [comment]
OMG didnt knew that option. i'm more used to gulp. I'll change it.

**Comment by gkatsev** [comment]
Heh, no worries.
@heff @mmcc do you know why travis is failing here?

**Comment by mmcc** [comment]
No clue, but re-running it fixed it.

**Comment by eXon** [comment]
It looks like every PR I do the build fails. I'm doomed.

**Comment by eXon** [comment]
I'm now using grunt-browserify to run watchify. However, here is the sad part: if we use browserify:watch with all other tasks in the watch, it doesn't work. 

I personally don't want to run everything when I save a file (especially that Karma is taking forever to open and close the browser). Using `grunt browserify:watch` now give us a way to develop and rebundle the javascript in a few seconds instead of over 30 secs. 

I would rather run everything once I'm done with what I'm doing.

**Comment by gkatsev** [comment]
I think that sounds fine. `browserify:watch` is just for development and you should make sure to rerun `grunt build` and `grunt test` and what not before finishing up.

**Comment by gkatsev** [comment]
Anyway, LGTM

**Comment by heff** [comment]
lgtm

**Pull request merged**
