### PR TITLE
fix multiple assignments in var statements

### PR DESCRIPTION
**Pull request by rphv**
fixed var statements in `player.js` with multiple assignments as per the [Code Style Guide](https://github.com/videojs/video.js/blob/master/CONTRIBUTING.md#code-style-guide).

### CODE REVIEW

**Comment by heff** [comment]
Interesting, I'd forgotten that rule was in there. Thanks for the cleanup help. While that rule is there, if you look around we actually moved to using the single-var method with new code.

If @gkatsev likes multiple vars now, that's actually what I'd prefer now, but otherwise we don't need this to turn into a debate and we'll just keep going with what we're doing, and then do a big style cleanup with the next major version to make everything consistent.

**Comment by mmcc** [comment]
So much +1 for multiple vars. I've actually done a bit of this already in a branch I've got open, so for the sake of merge conflicts, I think we should just update these as we touch classes while working on the next version, then do one last final cleanup before the release.

**Comment by heff** [comment]
@gkatsev any objections? (Gary is the maintainer of the internal Brightcove javascript style guide, which the video.js style guide is closely tied to).

**Comment by heff** [comment]
I'm going to close this issue until we've resolved #1812 (add ES6 transpiler). That will be a more natural point to discuss and change our var style, which this issue should wait for a decision on. (Assuming there isn't a consensus before then)

Thanks again for the contribution @rphv.

**Pull request closed without merging**
