### PR TITLE
delegate canPlayType to canHandleSource

### PR DESCRIPTION
**Pull request by saxena-gaurav**

### CODE REVIEW

**Comment by pam** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: a433d9ef44c5a60e38183c9ebf046a4246eb701d
Build details: https://travis-ci.org/pam/video.js/builds/89110214

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by gkatsev** [comment]
I don't quite understand these changes. Did the previous implementation not delegate to source handlers that were attached to a tech?

**Comment by gkatsev** [comment]
Now that I'm reading more into this, I think this is not what we want. If anything, we'd want `canHandleSource` to delegate to `canPlayType` for that half of the check.
Maybe `canPlayType` can check `canHandleSource` if a `canPlayType` isn't available on the source handler?

**Comment by gkatsev** [comment]
Discussed with @saxena-gaurav offline. An issue was code duplication but we decided that we are OK with it in this case until we can spend time on making `canHandleSource` delegate to `canPlayType` or something.

**Pull request closed without merging**
