### PR TITLE
Update link to true destination to save redirect

### PR DESCRIPTION
**Pull request by hubdotcom**

### CODE REVIEW

**Comment by gkatsev** [comment]
We probably should just make the site work with either one and not do a redirect. `www` is to 2002.
@heff ?

**Comment by heff** [comment]
It's actually an issue with hosting a domain on s3, or at least was when we did the last site. It requires/required a subdomain. It's worth verifying because I agree non-www is better.

**Comment by hubdotcom** [comment]
Does require Amazon DNS but a potential solution https://aws.amazon.com/blogs/aws/root-domain-website-hosting-for-amazon-s3/

**Comment by gkatsev** [comment]
This has been fixed.

**Pull request closed without merging**
