### PR TITLE
feat: enable responsive controls on fullscreen 

### PR DESCRIPTION
**Pull request by ipadilla4**
A client reported that control buttons are not positioned correctly when player is full-screened and screen is small.

Currently we are excluding our responsive controls on fullscreen and changes include removing that. This solves the issue for small screens. Also added _!important_ rule to override BC skin properties and hide controls when necessary.

### CODE REVIEW

**Review by gkatsev — APPROVED** [review]

**Review by misteroneill — APPROVED** [review]
This is good, I think, but we should look at our internal BC skin to see if we can change the specificity such that the `!important` is not necessary.

**Comment by amtins** [comment]
@gkatsev, @misteroneill we recently updated to the latest videojs version which contains this fix. However, this fix forces us to introduce the use of !important, which means we will have to do something like @infinite-persistence did [here](https://github.com/lbryio/lbry-desktop/commit/17a21e59dc4eb71b22875a99d562ee472cf4d5cb). In our case, this is not a good solution because we provide a library in which integrators can override some rules by increasing the specificity.

I don't know if I missed anything and what the BC means, but I think the !important is not necessary, based on my tests. @ipadilla4, maybe a reduced test case will help to understand why the !important is so important.

**Comment by gkatsev** [comment]
You're definitely right. We should look into and remove `!important`

**Comment by gkatsev** [comment]
@amtis this is being removed by https://github.com/videojs/video.js/pull/7449 and we'll get a patch released soon!

**Comment by gkatsev** [comment]
@amtins the change is in Video.js 7.15.7

**Pull request merged**
