### PR TITLE
feat(cors): add cors options to enable cookies on requests

### LINKED ISSUE #5438: Set crossorigin attr programmatically
## Description
I've been struggling with the crossorigin attribute; right now the implementation I have is a playlist, the first video should not have such attribute but the second does and I have tried multiple ways like:
* `player.setAttribute('crossorigin', 'anonymous')`
* `player.el_.setAttribute('crossorigin', 'anonymous')`
* `player.setAttribute('cors', 'anonymous')`

even pass it like 
```js
const options = {
  crossorigin: 'anonymous',
  cors: 'anonymous',
}

videojs(node, options)
```
So at this point, I wonder if there an API to do this (I found nothing on the documentation, and the source code only relates to this for close caption)

### plugins none,
 just programmatically trying to set for the next video

I'm aware that a workaround might be set it for the video tag and use another video tag later, but I was looking to pass it programmatically in a more elegant way... maybe creating a plugin that applies it automatically after checking the source or else.

### PR DESCRIPTION
**Pull request by citosid**
fixes #5438, #4851

## Description

Adds ability to send credentials in the XHR requests.

If the video the user needs to play is in a different domain and it is protected with a session, we need to configure the player so it will forward cookies along with the request, otherwise, the user will receive a 403.

This happens, for example, when playing videos from Akamai:

https://community.akamai.com/customers/s/question/0D50f00005Rtq3sCAB/media-services-on-demand-hls-manifests-are-different-for-firefox?language=en_US

## Specific Changes proposed

- Add crossorigin to the options object

## Requirements Checklist

- [x] Feature implemented / Bug fixed
- [x] If necessary, more likely in a feature request than a bug fix
  - [x] Change has been verified in an actual browser (Chome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by gkatsev** [comment]
Thanks for the PR! Been away last week due to holidays but I'm back now.

Can you revert all the style changes that aren't related to the changes in this PR? There's a lot that makes it hard to know what's changed.

**Comment by citosid** [comment]
Hello @gkatsev !

Sure, will do it and push again. I started also a [thread in slack][1]. Were you able to see it?

[1]: https://videojs.slack.com/archives/C43LGP955/p1577384899021100

**Comment by sodabrew** [comment]
I'm quite excited by this functionality and would also ask that you remove the style changes so I can easily grab a clean patch to test if this works for my site. For me, it is just the subtitles that are missing cross-origin cookies - I thought I saw a recent change related to this, but can't find it just now.

**Comment by sodabrew** [comment]
@citosid Could you update this PR so it can move forward? I still am in need of this functionality. I'd also be glad to post a new PR with a clean version of this change if you don't have time.

**Pull request closed without merging**
