### PR TITLE
Added a new loading spinner

### PR DESCRIPTION
**Pull request by heff**
It looks like this: http://codepen.io/heff/pen/QjjZVW

Good?

### CODE REVIEW

**Comment by gkatsev** [comment]
It looks kind of weird when both the heads reach the top.

**Comment by heff** [comment]
I think I see what you mean, and I think it could be because the animation didn't cover from 0 to 100%. Does it look any better now?
http://codepen.io/heff/pen/QjjZVW

**Comment by Globulopolis** [comment]
@heff yes, much better :)

**Comment by heff** [comment]
Updated so the two things don't show through each other at the top.
http://codepen.io/heff/pen/ZbQePZ

**Pull request closed without merging**
