### PR TITLE
Export event helpers on videojs object

### PR DESCRIPTION
**Pull request by gkatsev**

### CODE REVIEW

**Comment by dmlap** [comment]
:+1:  You misspelled "videojs" in your commit comment, though

**Comment by gkatsev** [comment]
@dmlap I'm not sure what you're talking about. :stuck_out_tongue_winking_eye:

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 718a164f6c2a4f930ad655be6942bfdf056de5e1
Build details: https://travis-ci.org/pam/video.js/builds/76326801

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by heff** [comment]
lgtm!

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 873bb38694be953e5cfc28f172cad3561b9c1d51
Build details: https://travis-ci.org/pam/video.js/builds/76327079

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Pull request closed without merging**
