### PR TITLE
Allow the control bar to show on the error screen

### LINKED ISSUE #3323: Allow us to change sources even if we hit a media that is not supported in the currentbrowser
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

When you select a media for example webm in Internet Explorer it causes it to show an error that says this media is not supported or something similar to that but you carn't do anything else, you carn't change source or do anything else. With ogv.js it supports the ogv format in Internet Explorer and Microsoft Edge with js.

The only way to get the player to do anything is to refresh the page and I think it selects the media it supports. But again if you select webm from source switcher it causes the error and you carn't do anything else until you refresh again. Please could you support changing sources even if the media your on is not supported. Would solve having to refresh everytime.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.10.1
#### browsers
what browser are affected?
All that doint support the format you click on
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.
https://github.com/kmoskwiak/videojs-resolution-switcher

### PR DESCRIPTION
**Pull request by paladox**
## Description
Please describe the change as necessary.
If it's a feature or enhancement please be as detailed as possible.
If it's a bug fix, please link the issue that it fixes or describe the bug in as much detail.

## Specific Changes proposed
Please list the specific changes involved in this pull request.

## Requirements Checklist
- [ ] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](http://jsbin.com/axedog/edit?html,output))
- [ ] Reviewed by Two Core Contributors

Allows us to change src to something that will work without needing to refresh the page.

Fixes #3323

### CODE REVIEW

**Comment by paladox** [comment]
@gkatsev Hi, I managed to get control bar to show, but the error message and the big x doint disappear when I choose a different source that works.

**Comment by gkatsev** [comment]
#3323 doesn't need a fix without the bigger issue at hand that needs fixing: having videojs try and choose a different source when an error occurs https://github.com/videojs/video.js/issues/1316.
You should be able to change the source just fine by calling `error(null)` like I mentioned in my comment on #3323: https://jsbin.com/cugeta/4/edit?html,js,console,output

**Comment by paladox** [comment]
But if the control bar is hidden, we carn't go into it to change the source. Unless that's what  error(null)  does.

**Comment by gkatsev** [comment]
Yes, `player.error(null)` tells videojs to ignore the error and hide the error display.

**Comment by paladox** [comment]
Ok thanks, if we update the resolution plugin, would that work.

**Comment by gkatsev** [comment]
Yeah, I think if the issue is that you can't switch resolutions, it should be fixed in that plugin. You can listen to the `error` event to make sure that you're only disabling the correct error.

**Comment by paladox** [comment]
Ok thanks.

**Pull request closed without merging**
