### PR TITLE
Update almost all links to HTTPS

### PR DESCRIPTION
**Pull request by CoWinkKeyDinkInc**
## Description

After running into a simple error that was fixed by replacing it from HTTP to HTTPS, I made this PR to make it so websites that can serve HTTPS will serve it properly.
## Specific Changes proposed

This changes websites that work with HTTPS to use HTTPS links instead of the insecure HTTP links.  This also edits one link from whatwg.org to it links to the same article again.  This does not change links from w3c as I've found that it 404'd.
## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Unit Tests updated or fixed
  - [] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](http://jsbin.com/axedog/edit?html,output))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by gkatsev** [comment]
Thanks for the PR. Changing most of the links over to HTTPS makes sense to me.
Though, there's definitely links that either need to stay as http because they're used in tests or because the https urls don't currently work (for example, videojs.com itself doesn't work well over https right now).
In addition, URLs in documentation should probably just use the protocol-relative urls rather than http/https.

**Comment by gkatsev** [comment]
Actually, most of the links can probably just be protocol relative as well.

**Comment by CoWinkKeyDinkInc** [comment]
@gkatsev Don't worry, I didn't change any of the video.js links because I noticed they don't work with HTTPS.  I'll revert the HTTPS change on the test folders if you want.

**Comment by CoWinkKeyDinkInc** [comment]
I don't know how to make protocol relative URLs

**Comment by gkatsev** [comment]
Protocol relative urls just have `//` in front of them instead of `https://` or `http://`.

**Comment by CoWinkKeyDinkInc** [comment]
Alright, I'll add these commits tomorrow

**Comment by CoWinkKeyDinkInc** [comment]
So I reversed the changes to the text files, I think all the links that could use protocol relative URLS are already using them.

**Comment by gkatsev** [comment]
Unfortunately, this got pretty out of date with master (partly my fault for not reviewing it in time). I'm still not sure that this is quite necessary but you can open a new PR if you update this.

**Comment by CoWinkKeyDinkInc** [comment]
Okay, I'll take a look at it again and fix anything if it's needed.  Do you know why the builds failed btw?

**Pull request closed without merging**
