### PR TITLE
port #2412 to master

### PR DESCRIPTION
**Pull request by gkatsev**

### CODE REVIEW

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: ae3a3878081aa7970c6ab2bce322101409486cf0
Build details: https://travis-ci.org/pam/video.js/builds/73081106

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: b044ad4a1989177fcc423ab1dd10a31aca2c1480
Build details: https://travis-ci.org/pam/video.js/builds/73081344

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by gkatsev** [comment]
@pam retry

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: b044ad4a1989177fcc423ab1dd10a31aca2c1480
Build details: https://travis-ci.org/pam/video.js/builds/73082659

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by gkatsev** [comment]
@pam retry

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: b044ad4a1989177fcc423ab1dd10a31aca2c1480
Build details: https://travis-ci.org/pam/video.js/builds/73084340

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by gkatsev** [comment]
I give up, @pam

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: e7d9c805bbb1c09797ef5129f9c18b02340aaa62
Build details: https://travis-ci.org/pam/video.js/builds/74138763

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 044dcf5561e9645f75d80f7b2c8112bc64fce19a
Build details: https://travis-ci.org/pam/video.js/builds/74446531

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: fee157de78e37816026eea82d7746c714dbf9eb5
Build details: https://travis-ci.org/pam/video.js/builds/74629291

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by gkatsev** [comment]
This should wait for #2412 in case there are other changes we want to make.

**Comment by gkatsev** [comment]
Closing this in favor of a new PR that would remove all the codes.

**Pull request closed without merging**
