### PR TITLE
fix (sass): import path has cwd once again

### PR DESCRIPTION
**Pull request by tsi**
This fixes a sass compile error we got after upgrading to 7.x
Same as https://github.com/videojs/video.js/pull/4061 but for v7.x

### CODE REVIEW

**Comment by tsi** [comment]
I see now that this was done intentionally as part of a move to use dart-sass, correct?
https://github.com/videojs/video.js/commit/3e105719babaf2ce6f98792bc6b5f9e349d9dfca

Do we have some kind of upgrade instruction for people coming from 5.x or 6.x ?
I just went over everything in https://github.com/webpack-contrib/sass-loader/issues/435 and I still get the same error I did with `node-sass`

**Comment by gkatsev** [comment]
Yeah, this was done as part of the switch to dart-sass. As you can see the build is failing with this change. I'm not sure how to reconcile the two.
Maybe we can update the path after we build locally and before we publish so the published version has `import 'node_modules/` but during build it has `../../node_modules`?

**Comment by tsi** [comment]
I still don't get something. even if I move to [our project](https://github.com/cloudinary/cloudinary-video-player) to `dart-sass`, I still get the same error:
```
SassError: Can't find stylesheet to import.
      ╷
    5 │ @import "../../node_modules/videojs-font/scss/icons";
      │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
And if I change to :
`@import "node_modules/videojs-font/scss/icons";`
Everything works like it should.
So I'm really confused. does this work anywhere else? what are we doing differently?

**Comment by gkatsev** [comment]
Oh, I wonder if this is happening because the location of files is different depending on whether it's used during the build in the video.js source directory vs being imported in sass from node_modules/video.js/src/css...
Also, potentially related to where videojs-font is installed along with video.js.

@tsi can you show me the output of `npm ls video.js` and `npm ls videojs-font`? Also, I assume just `node_modules/...` without the `../../` does work when you import it in your project?

**Comment by tsi** [comment]
> location of files is different depending on whether it's used during the build in the video.js source directory

I think that's spot-on
when you develop and build `video.js`, the `videojs-font` package is located in `video.js`'s (your repo's) `/node_modules`. but when I'm developing, the `videojs-font` package is located in my own `/node_modules`, right next to `video.js`.

> can you show me the output of npm ls video.js and npm ls videojs-font

```
% npm ls video.js    
...
├─┬ video.js@7.6.6 
│ └─┬ @videojs/http-streaming@1.10.6
│   └── video.js@7.6.5 
├─┬ videojs-contextmenu@1.2.2
│ └── video.js@5.20.5 
├─┬ videojs-contrib-ads@6.6.5
│ └── video.js@7.6.5 
├─┬ videojs-ima@1.7.1
│ └── video.js@7.6.5 
└─┬ videojs-per-source-behaviors@2.1.0
  └── video.js@7.6.5 
```

```
% npm ls videojs-font
...
├─┬ video.js@7.6.6
│ ├─┬ @videojs/http-streaming@1.10.6
│ │ └─┬ video.js@7.6.5
│ │   └── videojs-font@3.2.0  deduped
│ └── videojs-font@3.2.0 
├─┬ videojs-contextmenu@1.2.2
│ └─┬ video.js@5.20.5
│   └── videojs-font@2.0.0 
├─┬ videojs-contrib-ads@6.6.5
│ └─┬ video.js@7.6.5
│   └── videojs-font@3.2.0  deduped
├─┬ videojs-ima@1.7.1
│ └─┬ video.js@7.6.5
│   └── videojs-font@3.2.0  deduped
└─┬ videojs-per-source-behaviors@2.1.0
  └─┬ video.js@7.6.5
    └── videojs-font@3.2.0  deduped
```

> Also, I assume just node_modules/... without the ../../ does work

It does, and I assumed it should work for you too.

**Comment by gkatsev** [comment]
So, I think I found a workaround that won't require doing weird stuff. The sass api includes a `--load-path` option and if we use we can get it to build locally with the import being `node_modules/...`.

@tsi Can you add `--load-path='./'` to the package.json lines for `build:css:cdn` and `build:css:default`? They should look like:
```sh
sass --load-path='./' --no-source-map src/css/vjs-cdn.scss dist/alt/video-js-cdn.css
```
and 
```sh
sass --load-path='./' --no-source-map src/css/vjs.scss dist/video-js.css
```

**Comment by tsi** [comment]
Sure, done, will it pass the build test?

**Comment by gkatsev** [comment]
Looks like it passed, 🎉. We'll likely be able to release next week.

**Comment by tsi** [comment]
You're quick! Thanks!!

**Comment by tsi** [comment]
@gkatsev no merge?

**Comment by gkatsev** [comment]
It'll happen this week. We have a policy of requiring two approvals for PRs and the other approvers were out last week.

**Pull request merged**
