### PR TITLE
Added `useractive` and `userinactive` event API docs

### PR DESCRIPTION
**Pull request by tamlyn**
I've added dummy entries to player.js and rebuilt the docs. Hope that's right.

### CODE REVIEW

**Comment by thijstriemstra** [comment]
I've also did this before and was told not to include the generated .md API doc in the PR, they update this during a new release.

**Comment by vijaykumargangani1110** [comment]
"/>

**Comment by vijaykumargangani1110** [comment]
xssfileupload html

**Comment by vijaykumargangani1110** [comment]
1461117_603139013080650_917628146_n

**Comment by vijaykumargangani1110** [comment]
1461117_603139013080650_917628146_n

**Comment by vijaykumargangani1110** [comment]
HIIIII

**Comment by vijaykumargangani1110** [comment]
sfhksvksvbk

**Comment by vijaykumargangani1110** [comment]
svbkvdsbnkvdzbkn

**Comment by heff** [comment]
@tamlyn thanks for the help!

(I merged in the first commit without the built docs.)

**Pull request closed without merging**
