### PR TITLE
Adding galician

### PR DESCRIPTION
**Pull request by ablunier**
## Description
Adding galician language strings

## Specific Changes proposed
Added gl.json file.

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by gkatsev** [comment]
Thanks!
Would you be able to run `grunt check-translations` so https://github.com/videojs/video.js/blob/master/docs/translations-needed.md#translations-needed gets updated?

**Comment by ablunier** [comment]
Done @gkatsev!

**Comment by gkatsev** [comment]
Thanks @ablunier. While I have you, are you able to get the other items translated? If not, that's fine too.

**Comment by ablunier** [comment]
Yes @gkatsev, I will translate the missing items too :)

**Pull request merged**
