### PR TITLE
Expose some dom.js methods

### LINKED ISSUE #2683: 5.0: consider exposing some dom.js methods
We are currently using some methods from `dom.js` in our project.
We can not directly `import` that file from outside of the video.js package, as it seems this is not allowed by browserify / babelify.

This means we now have a copy of some of these functions, which is a shame.

It would be better if either these functions are exposed separately or if the whole `dom` file is exposed.

We currently use these methods:

* `createEl`
* `hasElClass`
* `addElClass`
* `removeElClass`

Is this something that you would consider changing?

### PR DESCRIPTION
**Pull request by nickygerritsen**
This should fix #2683 by adding the four mentioned methods to videojs. I also added some simple tests that these methods exist and are correct aliases, but I'm not sure whether these should actually be in `api.js`?

### CODE REVIEW

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: cfe52125e37559f26b60257117a3149b4b87dc41
Build details: https://travis-ci.org/pam/video.js/builds/86340136

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by nickygerritsen** [comment]
....that Vista saucelabs thing...

**Comment by gkatsev** [comment]
Yeah, I'm trying to figure out why it's busted. Thanks for the PR.

**Comment by misteroneill** [comment]
Quick note. This looks good, but I have a [very similar branch](https://github.com/misteroneill/video.js/tree/expose-dom-helpers) (rebased on my `modal-dialog` branch, which is why there's no PR yet) that does this and a bunch of other things like rewriting the `*Class` methods to use `classList` where available and improve tests.

**Comment by nickygerritsen** [comment]
Thanks @misteroneill I like your PR even more :)

**Comment by misteroneill** [comment]
I opened a PR for my branch: #2754

**Comment by gkatsev** [comment]
Closing in favor of #2754. Thanks @nickygerritsen for getting this started.

**Pull request closed without merging**
