### PR TITLE
Add ISSUE_TEMPLATE for github.

### PR DESCRIPTION
**Pull request by gkatsev**
See https://github.com/blog/2111-issue-and-pull-request-templates

### CODE REVIEW

**Comment by dmlap** [comment]
Cool! Notes:
- link to jsbin.com/axedog for the reduced test cases?
- The STR numbering doesn't render correctly in github markdown right now

**Comment by gkatsev** [comment]
Yeah, the number doesn't render correctly without content. When new issues are included, they're in "write" mode and not "preview" mode, so, it should be OK.

**Comment by dmlap** [comment]
The PR template is awesome for new features. I wouldn't want to set the bar that high for simple bug fixes, though. Any way to split the difference?

**Comment by gkatsev** [comment]
Not sure. A lot of that applies should apply to "simple bug fixes" as well. Maybe we just need better/simpler wording.

**Comment by heff** [comment]
Nice! Love this feature. lgtm

**Comment by gkatsev** [comment]
@dmlap I updated the wording in the PR Template. Please take another look.

**Comment by dmlap** [comment]
:+1:

**Pull request closed without merging**
