### PR TITLE
Added scss files to dist folder

### PR DESCRIPTION
**Pull request by mmcc**
Also moved the `style-injection-task` to the build/tasks directory.

The cool thing about this is it allows someone with a Sass workflow to import our SCSS files directly into their own, so there doesn't need to be an additional build step. Dogfooding ftw.

### CODE REVIEW

**Comment by gkatsev** [comment]
LGTM

**Comment by heff** [comment]
@mmcc https://github.com/mmcc/video.js/pull/8

**Comment by heff** [comment]
lgtm!

**Comment by heff** [comment]
Also we've switched it to instead include the original source files in the npm package instead of copying them to dist.

**Pull request merged**
