### PR TITLE
fix: remove CaptionsSettingsMenuItem when TextTrackSetting is not inc…

### LINKED ISSUE #4996: Remove CaptionsSettingsMenuItem when TextTrackSettings is not included
### 🆕🐥☝ First Timers Only.

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

[About First Timers Only](http://www.firsttimersonly.com/).

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [x] 🙋 **Claim this issue**: Comment below.

- [x] 📝 **Update** the file [src/js/control-bar/text-track-controls/captions-button.js](https://github.com/videojs/video.js/blob/master/captions-button.js) in the `video.js` repository (press the little pen Icon) and edit the line as shown below.

``````diff
@@ -51,7 +51,8 @@ class CaptionsButton extends TextTrackButton {
   createItems() {
     const items = [];
 
-    if (!(this.player().tech_ && this.player().tech_.featuresNativeTextTracks)) {
+    if (!(this.player().tech_ && this.player().tech_.featuresNativeTextTracks) &&
+      this.player().getChild('textTrackSettings')) {
       items.push(new CaptionSettingsMenuItem(this.player_, {kind: this.kind_}));
 
       this.hideThreshold_ += 1;
``````

- [x] 💾 **Commit** your changes

- [x] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions

Leave a comment below!

This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).

### PR DESCRIPTION
**Pull request by vsoren**
## Description
Removes the CaptionsSettingsMenuItem when TextTrackSettings is not included.

Fixes #4996 

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Change has been verified in an actual browser (Chome, Firefox, IE)
  - [x] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](http://jsbin.com/axedog/edit?html,output))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by ldayananda** [comment]
Thanks for the PR @vsoren! Looks like you found some out of date tests-- if you take a look at the [source code](https://github.com/videojs/video.js/blob/master/src/js/tracks/text-track-settings.js#L492) and then the [tests that fail](https://github.com/videojs/video.js/blob/2f96914b8e570fc16d19b546fa0bfe26ab0b727c/test/unit/tracks/text-track-settings.test.js#L181), you'll notice that `'.vjs-texttrack-settings'` should really be `'.vjs-text-track-settings'`

**Comment by ldayananda** [comment]
In fact, specifically for the [first test that fails](https://github.com/videojs/video.js/blob/master/test/unit/tracks/text-track-settings.test.js#L176-L185) , it doesn't seem like text-track-settings.test.js is right place for it. It should probably be removed and rewritten for the [CaptionsSettingsMenuItem](https://github.com/videojs/video.js/blob/master/src/js/control-bar/text-track-controls/caption-settings-menu-item.js#L54-L57).

For this PR, I would be ok with removing that first test.

**Comment by gkatsev** [comment]
So, after looking at this, I think we want to change the way the tests are. The tests look for the caption settings menu item and then "click" it to open the modal dialog. With this fix, we don't have a default caption settings menu item unless there are captions that are emulated. I'll make a PR for the test fixes.

**Comment by gkatsev** [comment]
I guess it just started failing because we weren't adding it unconditionally anymore.
@vsoren I made a PR against your branch (https://github.com/vsoren/video.js/pull/1), once you merge that PR, we can merge this PR in!

**Comment by vsoren** [comment]
@gkatsev The PR on my branch has been merged. :)

**Comment by gkatsev** [comment]
@vsoren thanks!

**Pull request merged**
