### PR TITLE
docs: add an example Angular integration.md

### PR DESCRIPTION
**Pull request by xx4159**
## Description
Instructions for Angular integration.

## Specific Changes proposed
add guides/angular.md

## Requirements Checklist
- [ ] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Change has been verified in an actual browser (Chome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [x] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by gkatsev** [comment]
Hey, that looks great. Can I trouble you to create a demo on a site like codesandbox.io? This is especially because I'm very unfamiliar with Angular.

**Comment by xx4159** [comment]
@gkatsev
Sorry, I'm late. I created a demo for Angular.
You can see here 😀   https://stackblitz.com/edit/angular-ivy-dk82zp?file=src/app/vjs-player.component.ts

**Comment by gkatsev** [comment]
@xx4159 awesome! No worries, care to submit another PR to add a link to the doc?

**Comment by gkatsev** [comment]
Actually, I think I may use yours as a base rehost it somewhere we can make changes to so we don't have to ping you for small changes like updating the Video.js version or something.

**Pull request merged**
