### PR TITLE
fix: hide font-icons from assitive technology

### LINKED ISSUE #3982: Font icons should be hidden from assistive technology (screen readers)
## Description

The font icons are inserted into the page using special characters in the CSS, e.g.:

````
.vjs-icon-play:before, .video-js .vjs-big-play-button:before, .video-js .vjs-play-control:before {
    content: "\f101";
}
````

giving:

````
<button class="vjs-play-control vjs-control vjs-button vjs-paused" type="button" aria-live="polite" title="Play" aria-disabled="false">
    <!-- Icon is inserted here in the DOM -->
    <span class="vjs-control-text">Play</span>
</button>
````

Screen readers include the `\f101` character in the name of the button, together with the `vjs-control-text`. No problems have been reported with this yet, but the extra character can be seen, for example, with VoiceOver on macOS, which displays the spoken text on the screen. This extra character will also be displayed on Refreshable Braille Displays, and could cause confusion.

## Recommendation

The font icon should be inserted in a `<span aria-hidden="true"></span>` inside the control, so that the special character is hidden from screen readers as purely decorative.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
v5.15
#### browsers
Browser and screen readers including IE11 & JAWS18, Firefox & NVDA, Safari & VoiceOver
#### OSes
Windows 7, macOS
### plugins
no.

### PR DESCRIPTION
**Pull request by gkatsev**
Wrap font-icons in a span with aria-hidden=true on it.

Fixes #3982.

### CODE REVIEW

**Comment by OwenEdwards** [comment]
Doesn't work for the Big Play Button. Otherwise LGTM.

**Comment by OwenEdwards** [comment]
@gkatsev, as a side note - given how simple these changes were (nice work!), I wonder if we should also put the `MenuItem` text in its own `<span class="???">`? It could have its own class name, and it **wouldn't** have `aria-hidden`, but may give us consistent DIV/SPAN structuring so that we can make changes in v6 without changing the DOM?

Come to think of it, we could also insert a `<span aria-hidden="true" class="vjs-icon-placeholder"></span>` at the start of the `MenuItem` too, which could be a placeholder in case we want to implement an icon and visible label text, as I mentioned in https://github.com/videojs/video.js/issues/3699#issuecomment-275264808, item 2?

**Comment by gkatsev** [comment]
Adding the span is additive, so, we can always add it at a later date. However, putting the menuitem text into its own span sounds like a good idea.

**Comment by gkatsev** [comment]
I opened up https://github.com/videojs/video.js/issues/4017 for the menuitem DOM structure changes

**Pull request merged**
