### PR TITLE
Update es.json

### PR DESCRIPTION
**Pull request by RevinKey**
[translations-needed.txt](https://github.com/videojs/video.js/files/735513/translations-needed.txt)

## Description
Added "Play Video" for BigPlayButton's ControlText

## Specific Changes proposed
Added    "Play Video": "Reproducción Vídeo",  to the es language JSON 

## Requirements Checklist
- [ ] Feature implemented 
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Change has been verified in an actual browser (Chome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](http://jsbin.com/axedog/edit?html,output))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by BrandonOCasey** [comment]
Thanks for the PR @RevinKey! Are you able to run the grunt check-translations task to update `translations-needed.md`? Your PR looks good other than that.

**Comment by RevinKey** [comment]
@BrandonOCasey I am able to run grunt check-translations locally and I see the change.

**Comment by mister-ben** [comment]
After you've run the task, just add the updated translations-needed.md to the PR. Thanks

**Comment by gkatsev** [comment]
@RevinKey any updates? Thanks!

**Comment by RevinKey** [comment]
Sorry for delay, it is updated now

**Pull request merged**
