### PR TITLE
RTMP Live Timed Metadata

### PR DESCRIPTION
**Pull request by cladera**
Populate RTMP onCuepoint data to a in-band-metadata text track using WebVTT standard.

### CODE REVIEW

**Comment by cladera** [comment]
I open this PR against master branch as @forbesjo requested.

I couldn't figure out any test though. Since it's a feature for live streams I don't know how I might test it. 

I could make Flash tech to trigger a fake 'cuepoint' event and ensure the metadata TextTrack is created. But, in my opinion, I would be testing EventEmitter and TextTrack rather than cuepoints feature its self, right? 

Any suggestions?

**Comment by vpezeshkian** [comment]
Any update on this PR? Any ETA?

**Comment by gkatsev** [comment]
This change also requires the swf to be updated with https://github.com/videojs/video-js-swf/pull/157

**Comment by gkatsev** [comment]
There is no ETA. Unless we decide not to merge this (low probably right now and seems simple enough), the main blocker is us testing and verifying it. Once we can do that, we can merge it in.

**Comment by cladera** [comment]
I really don't know how to test this feature. 

As I commented in [videojs/video-js-swf#157](https://github.com/videojs/video-js-swf/pull/157), in order to test this feature I'd either need a Live RTMP feed sending cuepoints periodically or mock it. 
I did not find a reliable RTMP feed to use for testing and even less sending cuepoints. Mocking a RTMP stream seems even more complicated.

Perhaps I'm facing the problem the wrong way. I'd really appreciate help in this one.

**Comment by gkatsev** [comment]
Yeah, testing the swf is very tricky. We've generally ended up verifying things manually.

**Comment by gkatsev** [comment]
Unfortunately, I'm unable to test this so cannot accept the changes. Considering that Google Chrome will soon be disabling flash by default really soon, I don't think it's a huge loss.

**Pull request closed without merging**
