### PR TITLE
Added type=button to buttons

### LINKED ISSUE #2470: Control buttons submit form, missing type="button" (5.0.0-rc.49)
In my web-application i have a player which is integrated in a form with a checkbox to mark uploaded video as deleted. My problem is that all control buttons of the player submit form, because they don't have type="button", default value is "submit" (http://www.w3.org/TR/html-markup/button.html).

Example: http://jsfiddle.net/sLsvLv0q/12/
Windows 8.1: Firefox 40, Chrome 44, IE 11

### PR DESCRIPTION
**Pull request by mmcc**
Fixes #2470

### CODE REVIEW

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: b40e8781f1f87976ed435744c8cd7dc7127ec3e2
Build details: https://travis-ci.org/pam/video.js/builds/75394605

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by mmcc** [comment]
Ha yes, yes I did mean that. Code is right, title is not. 



—

**Comment by heff** [comment]
lgtm

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: efc9f7083230dc1b57fbd2680c2fabd44e34b7e9
Build details: https://travis-ci.org/pam/video.js/builds/75506086

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Pull request closed without merging**
