### PR TITLE
Run 'npm audit fix' (but roll back videojs-standard version)

### PR DESCRIPTION
**Pull request by OwenEdwards**
Using the latest LTS version of `node.js` (v8.11.3), and `npm` (6.4.0), ran `npm audit fix` to update `package.json`.

Running `grunt` produces errors from `videojs-standard`, so I rolled back the version of that package for now.

### CODE REVIEW

**Comment by gkatsev** [comment]
Oops, looks like me merging the grunt-cli GK PR made conflicts here.

**Comment by OwenEdwards** [comment]
@gkatsev it was an easy fix :-)

**Comment by gkatsev** [comment]
Thanks @OwenEdwards!

**Comment by gkatsev** [comment]
I pushed up the change to upstream so that it'll run against browserstack to minimize any potential issues, but I don't foresee any. https://github.com/videojs/video.js/compare/pr-5386?expand=1

**Comment by gkatsev** [comment]
And it all passed.

**Pull request merged**
