### PR TITLE
Adding back caption-settings styles. Closes #2104

### LINKED ISSUE #2104: Add captions settings styles back
The captions setting styles were lost in a rebase along the way, so those need to be added back.

### PR DESCRIPTION
**Pull request by mmcc**

### CODE REVIEW

**Comment by mmcc** [comment]
dat stack trace.

**Comment by mmcc** [comment]
ping

**Comment by gkatsev** [comment]
I figured out why the errors failed. It's because when we switched to concise methods, our new method shadowed the global `setInterval`, so, we just kept calling ourselves. I'll have a PR for that in 30 seconds and afterwards, I'll take a look at this PR.

**Comment by mmcc** [comment]
@gkatsev sweet

**Comment by gkatsev** [comment]
These styles look great.
Though, seems like the text track display styles are incorrect.

**Comment by gkatsev** [comment]
I'll have a PR against this PR after lunch.

**Comment by heff** [comment]
@mmcc can you merge master to fix the tests?

**Comment by gkatsev** [comment]
Closing this in favor of #2112

**Pull request closed without merging**
