### PR TITLE
fix: init inactivity checker not until first play event

### PR DESCRIPTION
**Pull request by axten**
## Description
see #5076

## Requirements Checklist
- [x] Bug fixed
- [x] If necessary, more likely in a feature request than a bug fix
  - [x] Change has been verified in an actual browser (Chome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](http://jsbin.com/axedog/edit?html,output))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by gkatsev** [comment]
btw, I went ahead and made the linting fixes myself.

**Comment by axten** [comment]
sorry for the trail an error approach :(

**Comment by gkatsev** [comment]
no worries, I just made the edits in the github editor and it's configured differently and forgot it leaves extra trailing spaces on empty lines. Thought I'd spare you the back-and-forth on fixing super simple linting issues.

**Comment by gkatsev** [comment]
and the tests passed!

**Pull request merged**
