### PR TITLE
Changed Audio Track button title to 'Audio Track' and modified en.json

### PR DESCRIPTION
**Pull request by jbarabander**
## Description

Per discussion on #3565 I changed the audio track title to be 'Audio Track' instead of just 'Audio'
Additionally I updated the en.json.
## Specific Changes proposed
Modified en.json to have an entry for 'Audio Track'.
Modified the AudioTrackButton components controlText_ to be 'Audio Track'

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by gkatsev** [comment]
LGTM

**Comment by BrandonOCasey** [comment]
LGTM

**Comment by gkatsev** [comment]
Merged to stable. Thanks!

**Comment by jbarabander** [comment]
@gkatsev: Awesome!!!

**Comment by gkatsev** [comment]
@jbarabander happy to help. Thanks for your effort as well!

**Pull request closed without merging**
