### PR TITLE
Implement vjs-ended class

### LINKED ISSUE #1675: Add a has-ended class name
We have has-started but not has-ended. Now that we've moved to using class states for showing/hiding the poster image, we don't have a good way to re-show the poster when the video ends. And I'm sure there will be a number of other good uses for it. Plus I mentioned that we *might* have it in a training the other day, but I was wrong. :)

See: http://stackoverflow.com/questions/27022730/video-js-display-poster-image-at-end-of-video

### PR DESCRIPTION
**Pull request by mister-ben**
Adds a `vjs-ended` class when playback ends, and removes it on a replay. Closes #1675.

### CODE REVIEW

**Comment by heff** [comment]
Whoa, with tests even, very nice! I think we need to reset it on loadstart also, because a new source doesn't have to autoplay.

**Comment by mister-ben** [comment]
Ah yes of course it should reset then. Will add.

**Comment by dmlap** [comment]
[The spec](https://html.spec.whatwg.org/multipage/embedded-content.html#dom-media-ended), for reference.

**Comment by heff** [comment]
lgtm! @dmlap or anyone else, can we get a second confirmation?

**Comment by dmlap** [comment]
Looks good to me, too.

**Pull request closed without merging**
