### PR TITLE
Add Scottish Gaelic translation

### PR DESCRIPTION
**Pull request by gunchleoc**
## Description
Add Scottish Gaelic translation.

I used an industry-standard tool for the translation and ran the result through https://jsonlint.com/, so the JSON should be complete and valid.

## Specific Changes proposed
Add Scottish Gaelic translation

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Change has been verified in an actual browser (Chome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by mister-ben** [comment]
The script that builds the lang files is choking on this file for some reason. Is it UTF-8?

**Comment by gunchleoc** [comment]
This is why Travis rocks!

I have done a copy/paste into the de.json and resaved, that will hopefully ensure the correct file format.

**Comment by gunchleoc** [comment]
Thanks for merging! :)

Is there any way I can be notified of when I need to update my translation? I work on too many translations to watch all the repositories completely ;)

**Comment by mister-ben** [comment]
We _try_ to keep this doc up to date https://github.com/videojs/video.js/blob/master/docs/translations-needed.md. Do you have any ideas how other projects manage notifying translators and what works well?

**Comment by gunchleoc** [comment]
Usually translations are put on a translation platform for projects that have advanced. You could try https://hosted.weblate.org/ which is FLOSS and supports the JSON format. You can then push and pull - see documentation at https://docs.weblate.org/en/latest/admin/continuous.html

**Pull request merged**
