### PR TITLE
Revert "Extended canHandleSource in media files to consistently guess mi...

### PR DESCRIPTION
**Pull request by motorhead73**
...me types. Fixes #1833"

### CODE REVIEW

**Comment by heff** [comment]
@motorhead73 it looks like this was supposed to be fixed by #1974. Can you give some more background why this is needed?

@carpasse can you take a look at this one?

**Comment by gkatsev** [comment]
#1833 is a PR itself. This PR revents the changes in #1974/#1833. I think it could just be ignored.

**Comment by carpasse** [comment]
I think @gkatsev is right.
I had some trouble merging #1833 and I did another pull request with #1974 maybe @motorhead73 got confused because of that.

**Comment by gkatsev** [comment]
Closing...
Thanks @carpasse

**Pull request closed without merging**
