### PR TITLE
Remove src/js/json.js, replace with safe-json-parse

### LINKED ISSUE #867: Remove JSON shim to avoid eval() CSP issues
(updated title and description to describe the enhancement)

IE8 supports JSON in IE8 standards mode (the default), but not other browser modes. In 5.0 we should be able to ask video.js users who need to support JSON in other modes or older browsers to supply their own JSON shim. This way we can avoid Content Security Policy issues that come up, even when the shim isn't used. 

This shouldn't be removed in 4.0 because of the potential to break existing installs, including those that are still making Video.js work with IE6 & 7.

**Original Title + Description**

### eval() in vjs.JSON.parse forces use of 'unsafe-eval' in Content Security Policy in order for VideoJS to work

eval() in vjs.JSON.parse forces use of 'unsafe-eval' in Content Security Policy in order for VideoJS to work. Is there any chance the JSON parser will move to a non-eval()ing parser? 

In vjs.JSON.parse on line 7024 in video.dev.js:
```
j = eval('(' + text + ')');
```

### PR DESCRIPTION
**Pull request by dconnolly**
Use the tuple variant of safe-json-parse to shim JSON.parse where not
available without using eval() as json.js was before.

Fixes #867

### CODE REVIEW

**Comment by gkatsev** [comment]
Sweet. Also, we probably want to have better handling of errors when they happen. Not sure if we want to take care of it in here or as part of another PR.

**Comment by dconnolly** [comment]
Agreed on the error handling, this is just a simple swap out for now.

**Comment by heff** [comment]
lgtm

**Comment by heff** [comment]
Tests failed for a  non-obvious reason. Rerunning them.

**Pull request closed without merging**
