### PR TITLE
Defer the implementation of select functions in the tech to source handlers if they provide them

### PR DESCRIPTION
**Pull request by imbcmdth**
I wrote this to allow us to generically add "deferrable" functions in the tech. Right now we only need two but we could extend that later.

### CODE REVIEW

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 4b67a05d093f370cc8dcf93334c6cdfbcd87d572
Build details: https://travis-ci.org/pam/video.js/builds/88241048

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by pam** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: b7b0c122e24a093697d71e3ad82f8d05019f0207
Build details: https://travis-ci.org/pam/video.js/builds/88397726

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by gkatsev** [comment]
So, this basically just makes the `seekable` and `duration` functions into a generic function that delegates to the source handler?

**Comment by imbcmdth** [comment]
Yes. Seekable was already had a delegate but I felt that making it so that delegates can be added easily without replicating code was worth the effort.

**Comment by gkatsev** [comment]
LGTM

**Comment by gkatsev** [comment]
Also, yay, travis is finally reporting back again

**Pull request closed without merging**
