### PR TITLE
Change the relative routes for easy compilation

### PR DESCRIPTION
**Pull request by ricardosiri68**
## Description
Please describe the change as necessary.
If it's a feature or enhancement please be as detailed as possible.
If it's a bug fix, please link the issue that it fixes or describe the bug in as much detail.

## Specific Changes proposed
Please list the specific changes involved in this pull request.

## Requirements Checklist
- [ ] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](http://jsbin.com/axedog/edit?html,output))
- [ ] Reviewed by Two Core Contributors

changing the route to `videojs-font` this way don't crash when i try to import the scss module

### CODE REVIEW

**Comment by gkatsev** [comment]
so `sass` always runs relative to the root/where it's run from? Interesting...

**Comment by gkatsev** [comment]
@videojs/core-committers anyone else care to do a code review?

**Comment by nickygerritsen** [comment]
We have had a similar issue in a completely different project and solved it in a similar way.
So I guess LGTM

**Comment by gkatsev** [comment]
Thanks @nickygerritsen.

**Pull request closed without merging**
