### PR TITLE
Set lang="en" on the <html> tag in HTML files.

### PR DESCRIPTION
**Pull request by OwenEdwards**
## Description
Set the lang attribute on all <html> tags in HTML files (in /sandbox/ and /test/).

## Specific Changes proposed
 This is required for accessibility compliance, and will prevent these errors being reported by accessibility testing tools.

## Requirements Checklist
- [x] Bug fixed
- [x] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by gkatsev** [comment]
LGTM.

**Comment by nickygerritsen** [comment]
Yeah LGTM

**Comment by gkatsev** [comment]
@OwenEdwards how do you feel about trying to merge this in yourself? I know the contributing guide isn't great but I can let you know how it's done if you're up for it.

**Comment by OwenEdwards** [comment]
@gkatsev okay, how about we connect about this on Wednesday?

**Comment by gkatsev** [comment]
@OwenEdwards sounds good. I want to spread the merging ability to people who aren't just me :)

**Pull request closed without merging**
