### PR TITLE
Is chrome on edge return true

### PR DESCRIPTION
**Pull request by benjipott**
## Description
Fix videojs.isChrome() on windows 10 edge return true

Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) **Chrome**/42.0.2311.135 Safari/537.36 Edge/12.10136

### CODE REVIEW

**Comment by gkatsev** [comment]
LGTM.
Wondering if you were seeing any problems related to it or did you just notice that it was true?

**Comment by benjipott** [comment]
Juste notice it, on windows 10 edge, if vjs / plugin test videojs.browser.IS_CHROME return true i think this const should return false

**Comment by gkatsev** [comment]
yeah, we should definitely have it return the right value.

**Comment by nickygerritsen** [comment]
@benjipott I was thinking: because Edge has kinda a strange UA string, isn't it better to put some `IS_EDGE` check at the top and for others add an `!IS_EDGE && ...`?

I can imagine we later add a Safari check and it will break again, because Edge also contains `Safari`.

So i.e.:

```javascript
export const IS_EDGE = (/Edge/i).test(USER_AGENT);
export const IS_CHROME = !IS_EDGE && (/Chrome/i).test(USER_AGENT);
// etc.
```

**Comment by nickygerritsen** [comment]
OK LGTM :)

**Comment by misteroneill** [comment]
LGTM as well 👍

**Pull request closed without merging**
