### PR TITLE
Remove a bunch of code that tried to disable tracks by default

### PR DESCRIPTION
**Pull request by gkatsev**
I think that's all of it (plus probably some tests that are forthcoming).
I'll open it against master soon.

### CODE REVIEW

**Comment by gkatsev** [comment]
Nope, looks like there aren't any tests for this that need to be removed.

**Comment by heff** [comment]
Have we confirmed if this issue is fixed in Chrome? I got the impression it might at least be fixed in Canary. And fwiw, the captions still showed for me in desktop safari, even with the fix we're removing here. So if Chrome is fixed, not a huge impact I don't think. 

lgtm

**Comment by gkatsev** [comment]
I'll see exactly where it is fixed, it'll be good to document. However, I still think this is the right move, for better or worse.

**Comment by gkatsev** [comment]
Also fixes #2436.

**Comment by heff** [comment]
still lgtm

**Comment by forbesjo** [comment]
:+1:

**Comment by gkatsev** [comment]
Looks like stable chrome still shows tracks by default.

**Comment by gkatsev** [comment]
It's merged. https://github.com/gkatsev/video.js/commit/a02f0befbce7808aeb0d84f3a3cea817949a1cb2

**Pull request closed without merging**
