### PR TITLE
Added @vjs-font-path variable

### PR DESCRIPTION
**Pull request by iSimonWeb**
It's a simple PR.
I just need to be able to change the font path since I'm using video-js via bower and the "font" directory of my project is not a subpath of "css".

Awesome Vanilla plugin anyway! Thank you! :+1:

### CODE REVIEW

**Comment by heff** [comment]
Thanks for the help! So does this allow you to override the value of `vjs-font-path` then? Is there potentially a cleaner way we should be handling this for people who are including this via bower?

@mmcc thoughts?

**Comment by mmcc** [comment]
@heff No, this doesn't allow you to override the value of `vjs-font-path`. As far as I know, this really just cuts down the number of places you need to type your new font-path (which is helpful).

I'm fine with pulling this in, but it's going to be fairly short lived.

**Comment by iSimonWeb** [comment]
Thank you guys for the attention.
I've seen this approach in the Font-Awesome project
Here is the variable -> https://github.com/FortAwesome/Font-Awesome/blob/master/less/variables.less
And there is where are they using it -> https://github.com/FortAwesome/Font-Awesome/blob/master/less/path.less

Hope you'll appreciate :+1:

**Comment by heff** [comment]
Thanks @iSimonWeb!

**Pull request closed without merging**
