### PR TITLE
Update translations in Dutch

### PR DESCRIPTION
**Pull request by siebrand**

### CODE REVIEW

**Comment by siebrand** [comment]
Is there anything special I should do so someone can merge this?

**Comment by heff** [comment]
@siebrand thanks for the help! There's nothing else you need to do, it's just that most of us are tied up finishing video.js 5.0. We'll get this pulled in soon.

@thijstriemstra can you confirm these are good changes?

**Comment by thijstriemstra** [comment]
Ziet er goed uit (looks good to me)!

**Comment by gkatsev** [comment]
Thanks.

**Pull request closed without merging**
