### PR TITLE
rework build to seperate out ie8 specific sass

### PR DESCRIPTION
**Pull request by erikyuzwa**
## Description
* This is in reference to issue #3013 
* Slice out some identified lines of sass specific to `IE8` and create its own separate `.css` file if needed by developers

## Specific Changes proposed
* added `src/css/ie8.scss` to capture all ie8 specific sass.
* moved out some lines from `src/css/components/_control-bar.scss` which were ie8 specific.
* added some necessary modifications to the `grunt build` task to support this.

## Requirements Checklist
- [ ] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](http://jsbin.com/axedog/edit?html,output))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by gkatsev** [comment]
Moving the IE8 stuff to another sass file, unfortunately, won't fix the issue. It needs to be turned into a plain old css file (so, sass won't turn the special characters into utf8/unicode characters).
Also, we don't want to create any breaking changes in patch or minor releases. Would be nice if this extra file can just be appended together with the file generated from sass.

**Comment by gkatsev** [comment]
Also, wanted to thank you for getting started on this. Let me know if you can get to the changes above, otherwise, I can probably pull your changes in and make the other changes as well.

**Comment by erikyuzwa** [comment]
gotcha. Thanks for the extra clarifications @gkatsev - I should be able to take care of this. No worries at all.

**Comment by erikyuzwa** [comment]
the only thing outstanding is that the unminified `src/css/ie8.css` isn't being appended to `build/temp/video-js.css`

**Comment by gkatsev** [comment]
Having the temp file not include the ie8 piece is fine, I think.

**Comment by gkatsev** [comment]
While I think that `build/temp/video-js.css` is fine if it's missing, it does need to be in `dist/video-js.css`. Looking into what needs to change. Maybe we can still get it into `build/temp/video-js.css` anyway.

**Comment by gkatsev** [comment]
Ah, we can use `concat` to do this. I'll make a PR for this against your PR.

**Comment by gkatsev** [comment]
Made a PR for this, see https://github.com/erikyuzwa/video.js/pull/1
What it does is uses concat to add the ie8-only files into `build/temp/video-js.css` after the `sass` task compiles all the sass stuff into `build/temp/video-js.css`. Then we don't need the `cssmin` changes because the ie8 changes are already in the file.

**Comment by misteroneill** [comment]
Love this. LGTM.

**Comment by gkatsev** [comment]
landed in https://github.com/videojs/video.js/commit/d86d4b222203d460557697e6d7a411048d5e2d92 and https://github.com/videojs/video.js/commit/1ff9f381a23f571e427c713ea459f1436037d87a.
Thanks @erikyuzwa for starting this!

**Pull request closed without merging**
