### PR TITLE
Bugfix for dispose when changing techs.

### PR DESCRIPTION
**Pull request by saxena-gaurav**
Credits to @vasklund for the bug fix. Thank you for the in-depth writeup to explain the issue. 
Adding the unit test in this PR.

### CODE REVIEW

**Comment by heff** [comment]
LGTM!

**Comment by heff** [comment]
This has been merged into stable.

**Comment by saxena-gaurav** [comment]
`PlaceHolder` usage has been removed here : https://github.com/videojs/video.js/pull/2057/
No need to merge this PR to master.

**Comment by gkatsev** [comment]
Actually we do to get the test case :)

**Comment by saxena-gaurav** [comment]
@gkatsev : Thanks. Added the test case against master branch here: https://github.com/videojs/video.js/pull/2129

**Comment by vasklund** [comment]
Awesome! So sorry I couldn't help with writing the test - but really nice to see this merged! Thanks for the help.

The following issues might be related and might also be solved:
https://github.com/videojs/video.js/pull/1793#issuecomment-71287428
https://github.com/videojs/video.js/issues/1505
https://github.com/videojs/videojs-contrib-hls/issues/222

Closing https://github.com/videojs/video.js/issues/1896.

**Pull request closed without merging**
