### PR TITLE
Fullscreen api changes to support custome fullscreen element

### PR DESCRIPTION
**Pull request by KevinBrogan**
### Modify isFullscreen to check the available fullscreen api if it exists.
I believe that the fullscreen api is available in every browser that is supported in vjs 7 since ie10 support has been dropped. This change will use the api if it is available, but the code should maybe be changed to only use the api. I would like feedback from the maintainers about this.

### Update jsdoc to indicate that undefined can be returned by setter.
A minor change. jsdoc pedantism.

### Modify requestFullscreen api call to use an element defined in options if it exists.
Setting options.fullscreenElement will cause the fullscreen routines to use that element as the fullscreen target isntead of the el_ target.

### Update fullscreen handling events to target document instead of bubbled player events.
This was required to get multiple players in a single page to syncronise their fullscreen states. Unfortunately, it has broken the fullscreen control bar unit test. I don't have the neccessary familiarity to rewrite the test in a satisfactory way and would like help from the videojs maintainers. I believe the unit test is incorrect, as true fullscreening of an element has been locked to user gesture events by the browser developers, so this feature can't actually be tested in an automated environment unless Karma can emit isTrusted user gesture events. All browsers that I tested in a live environment work as expected.

### Note
documentation still needs to be updated. I would like to wait till all unit tests pass before completing the documentation. As well, I have noticed that this code change fixes issue videojs/video.js#5745 as a sideeffect, although the change was not intentional.

- [Y ] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [Y ] Change has been verified in an actual browser (Chome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by gkatsev** [comment]
oops

**Comment by gkatsev** [comment]
@KevinBrogan hey would you be able to rebase this PR against master?

**Comment by KevinBrogan** [comment]
I gave it a shot but some internals have been changed and while I was able to fullscreen I wasn't able to unfullscreen. I'm on a bit of a crunch and ran out of time to investigate.

In the meantime, I've since resolved my issue by defining my own FullscreenToggle component and then setting the userActions.doubleClick option to function(){ this.controlBar.fullscreenToggle.handleClick(); }

If you're interested in the fullscreen toggle changes, give me a message on slack or on here and I can give you a copy paste.

**Comment by gkatsev** [comment]
Thanks @KevinBrogan, sorry that we never got this in. We'll take a look into getting it in anyway when we get the chance.

**Comment by vsx-sieber** [comment]
Any updates on this? In your guide you still mention that support for providing a custom `element` property in `fullscreen.options` is planned, but its been a while since it was first considered.

**Pull request closed without merging**
