### PR TITLE
Update el.json

### PR DESCRIPTION
**Pull request by arius28**
Added missing translations for Greek language

### CODE REVIEW

**Comment by mister-ben** [comment]
Thanks! Could you run `grunt check-languages`, which will update docs/translations-needed.md?

**Comment by arius28** [comment]
I can't say I know how to go about doing that unfortunately, but if you can direct me I 'd be more than willing...

**Comment by misteroneill** [comment]
Assuming you have the project checked out locally and NodeJS and NPM installed, you'll need to run the following commands on your command line.

- `npm install -g grunt-cli`: This will install the grunt-cli program, which will give you the `grunt` command.
- `npm install`: This will install various dependencies specific to the video.js project.
- `grunt check-languages`: This will run update the `docs/translations-needed.md` file automatically.

Then, you'll commit and push as normal.

**Comment by arius28** [comment]
Thanks for the info. I checked it out locally and tried to do it but it seems I 'm having problem with a babel/register dependency (because I got a newer version of babel installed if I understood correctly) and cannot run grunt successfully. I 'll try to get it working but can't promise so if at some point it is easier for someone to do this, please do...

**Comment by mister-ben** [comment]
I'm able to update, thanks to [this](https://github.com/blog/2247-improving-collaboration-with-forks). Thanks again.

**Comment by BrandonOCasey** [comment]
LGTM, Thanks @arius28 and @mister-ben

**Comment by misteroneill** [comment]
LGTM as well. Thanks @arius28 and @mister-ben (that's such a great feature, isn't it!?)

**Pull request merged**
