### PR TITLE
Allow the user to override videojs.formatTime using a custom function #2931

### PR DESCRIPTION
**Pull request by adamtal3**
## Description

https://github.com/videojs/video.js/issues/2931
## Specific Changes proposed

Updated format-time.js to check if videojs.formatTime is a function and if it is - use it.

### CODE REVIEW

**Comment by gkatsev** [comment]
Thanks for the PR. We appreciate the time and effort spent on it.

As it is right now, I don't think we can merge it because it assumes that videojs gets included as a global and doesn't allow a good mechanism for setting a custom format time method when videojs is required using browserify, webpack, or another bundler. Any solution to this problem must work regardless of how videojs is included and preferably not rely on separate global variables that videojs reads in.

Maybe what we want is to have a `setFormatTime` method that just takes a function and `formatTime` ends up using that method? As you mentioned in #2931, writing a custom string formatter isn't a great idea since users could end up with who knows what requirements.

I'm not sure it's necessary to keep this backwards compatible since it's a new feature; the fact that it worked previously is coincidental and not officially supported. Having a setter function would make it easier for us to change things internally without having to break the outward facing API. I'm not married to `setFormatTime`; let me know what you think about it.

**Comment by adamtal3** [comment]
I see your point.

Adding a setFormatTime function that will receive a formatting function will be a better approach (This is just the quickest).

How should I address this? Should I add a videojs.setFormatTime = .... when I import the ... from the time-format.js which will save the custom formatting function in a local/global variable in the file's scope?

Any specific instructions?

**Comment by gkatsev** [comment]
Probably the easiest is to have a `setFormatTime` method in both `video.js` and `format-time.js`  with the former calling the latter.
I'll think about it some more to see if there should be other constraints. The one thing I can think off is that the function being passed in only needs to get the time in seconds, since the `guide` would be a bit meaningless to it.

**Comment by thijstriemstra** [comment]
I'd also like to use this eventually, my plugins use a custom formatTime to add milliseconds, currently unsupported by video.js.

**Comment by gkatsev** [comment]
Closing this PR for now, the issue associated will remain open.

**Comment by cedricve** [comment]
@adamtal3 do you have any progress on this?

**Pull request closed without merging**
