### PR TITLE
chore: Add package-lock.json file.

### PR DESCRIPTION
**Pull request by misteroneill**
Adds the package-lock.json file for npm 5.

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by thijstriemstra** [comment]
What's the purpose of this file?

**Comment by gkatsev** [comment]
It's to make the development more reproducible once we move over to use npm5: https://docs.npmjs.com/files/package-locks

**Comment by thijstriemstra** [comment]
Thanks for the info @gkatsev. Looks very complex, SVN like (e.g. .svn dirs), too bad.

**Comment by gkatsev** [comment]
@thijstriemstra yw, thanks for looking at PR!
Hopefully, we won't really need to look at this file ever really. We just wanted to get this added separately/explicitly.

**Comment by thijstriemstra** [comment]
pro-tip: don't take a look at the diff. github is right, it's too big ;)

**Pull request merged**
