### PR TITLE
Move metadata to hidden folder and update references

### PR DESCRIPTION
**Pull request by piotr-cz**
## Description
Move metadata to hidden folder and update references

## Specific Changes proposed
This is an update to #3117, which moves files
- CONTRIBUTING.md
- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md

to own `.github` folder and fixes references in markdown files.

Reference: GitHub help > [Helping people contribute to your project
](https://help.github.com/articles/helping-people-contribute-to-your-project/)

## Requirements Checklist
- [ ] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](http://jsbin.com/axedog/edit?html,output))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by gkatsev** [comment]
Is there a specific reason why having it in the `.github` folder be better? I think I would prefer to keep them in the root of the project.

**Comment by gkatsev** [comment]
Thinking about this some more and talking with @BrandonOCasey, I think this would be good if we keep `CONTRIBUTING.md` in the root of the project but move the templates into the `.github` folder. `CONTRIBUTING.md` is/should be more than just a link that github links to at the top of issues.

**Comment by piotr-cz** [comment]
The reason is to move files that don't have to be in the root repo folder to clean it up.
I'll update PR to keep the `CONTRIBUTING.md` file where it is now.

**Comment by gkatsev** [comment]
Tests are failing for a separate reason.

**Pull request merged**
