### PR TITLE
Added lang: pl.json

### PR DESCRIPTION
**Pull request by kamilbrenk**
Added new language: Polish.

### CODE REVIEW

**Comment by gkatsev** [comment]
Thanks for the PR. Would you be able to update it to reflect the additions and changes in our new `en.json` template: https://github.com/videojs/video.js/blob/3ef88f8b80c3ae89fd31cfd6c0acfd1e02eeffd4/lang/en.json?

**Comment by kamilbrenk** [comment]
@gkatsev Ok, updated :)

**Comment by gkatsev** [comment]
Awsome. Thanks!

**Comment by gkatsev** [comment]
LGTM.

**Comment by dmlap** [comment]
LGTM

**Pull request closed without merging**
