### PR TITLE
Add volume tooltip

### PR DESCRIPTION
**Pull request by gjanblaszczyk**
## Description
Add tooltip for volume level so the user knows what they will change too. 
Maybe in the scope of WCAG "1.1.1 Non-text Content".

volume-tooltip

## Specific Changes proposed
Add volume level tooltip.

## Requirements Checklist
- [X] Feature implemented / Bug fixed
- [X] If necessary, more likely in a feature request than a bug fix
  - [X] Change has been verified in an actual browser (Chome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by gkatsev** [comment]
Hey, thanks for the PR. Totally forgot to take a look at it.

Two main things that is that we should document and perhaps make it easier to hide the volume tooltip. Also, if the inline:false volume panel is added as the last thing in the control bar, we should potentially have the tooltip show up on the left so that it doesn't go outside the player boundary.
Screen Shot 2020-11-17 at 18 29 15


@OwenEdwards thoughts on this?

**Comment by brandonocasey** [comment]
Having a tooltip is awesome, never realized that we were missing this!

**Comment by gjanblaszczyk** [comment]
Thanks for the review and sorry for the late response. I am planning to update this PR this week.

**Comment by gkatsev** [comment]
No worries @gjanblaszczyk, we appreciate the help. I was actually thinking of maybe merging this in and then having the direction get changed as a separate PR. However, if you think you can get this in soon, we may as well wait.

**Comment by gjanblaszczyk** [comment]
Hi @gkatsev, I am pretty busy right now, so I think it is a good idea to merge this and then to have a separate PR for the improvements. I am planning to back to it as soon as I have some free time.

**Comment by thijstriemstra** [comment]
> I was actually thinking of maybe merging this in and then having the direction get changed as a separate PR.

+1

**Review by gkatsev — APPROVED** [review]

**Comment by gkatsev** [comment]
I opened up #7145 to not forget fixing the issue of the volume control being the last item in the control bar.

**Pull request merged**
