### PR TITLE
fix: avoid black borders if poster doesn't fit 100% to ratio

### PR DESCRIPTION
**Pull request by axten**
## Description
sometimes there are rounding issues or the poster is not sized 100% correctly leading to black borders at top/bottom or left/right.

## Specific Changes proposed
make the poster cover the available space

## Requirements Checklist
- [x] Bug fixed
- [x] If necessary, more likely in a feature request than a bug fix
  - [x] Change has been verified in an actual browser (Chome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](http://jsbin.com/axedog/edit?html,output))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by gkatsev** [comment]
my main concern here is that cover allows the image to be cropped. This is probably fine if the poster is the same aspect ratio as the video so it only gets cropped by like a pixel to count for rounding with fluid mode. If the aspect ratio in the same, though, large portions of the poster could be cropped.

**Comment by axten** [comment]
your right, thats a kind of breaking change.
but I think that ok for fluid mode. Imho nobody should apply a 4:3 poster to a 16:9 video...

**Comment by gkatsev** [comment]
they shouldn't, but I've definitely seen it before.

@videojs/core-committers thoughts on this change?

**Comment by axten** [comment]
basically both cases can be fixed with additional css from the users so imho you should go with the solution that fits for the greater group of users

**Comment by gkatsev** [comment]
Yeah, I think this is too risky to move forward with. However, maybe it's something we could add in docs somewhere.
Thanks for the PR, though, @axten.

**Pull request closed without merging**
