### PR TITLE
Add playing event to docs.  Update play and playing event descriptions.

### PR DESCRIPTION
**Pull request by bclwhitaker**
It useful to know that there is an event that will fire when media is actually playing.  Since this is [required to be implemented by all techs per:](https://github.com/videojs/video.js/blob/3352346a74eca52328c14cad803e21587886bfbe/docs/guides/tech.md#required-events) I think its safe to include it here.

### CODE REVIEW

**Comment by heff** [comment]
Thanks Lee! These docs are actually generated from the source, so the update would need to be made there. https://github.com/videojs/video.js/blob/6cc1b5191bf3db67ffd302ba5931d6c1c49461ec/src/js/player.js#L436

**Comment by heff** [comment]
:pineapple:

**Comment by heff** [comment]
@bclwhitaker do you want to try this again by adding it to the player.js file?

**Comment by gkatsev** [comment]
Out of date.

**Pull request closed without merging**
