### PR TITLE
Fix track tests and ignore empty properties in tracks

### PR DESCRIPTION
**Pull request by gkatsev**

### CODE REVIEW

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: d26a646cde62028d23153da49ee07e2662e606a0
Build details: https://travis-ci.org/pam/video.js/builds/87566307

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by gkatsev** [comment]
Super weird that travis still hasn't replied since it actually passed.

**Comment by gkatsev** [comment]
@pam retry

**Comment by gkatsev** [comment]
@pam retry

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: d26a646cde62028d23153da49ee07e2662e606a0
Build details: https://travis-ci.org/pam/video.js/builds/87567160

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by gkatsev** [comment]
@pam retry

**Comment by pam** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: d26a646cde62028d23153da49ee07e2662e606a0
Build details: https://travis-ci.org/pam/video.js/builds/87570911

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by gkatsev** [comment]
If travis ever updates this, it'll be all green. But it actually *is* all green!

**Comment by misteroneill** [comment]
LGTM

**Pull request closed without merging**
