### PR TITLE
Support of pseudo-streaming

### PR DESCRIPTION
**Pull request by ange007**
Necessary functions for pseudo-streaming.
https://github.com/videojs/video-js-swf/issues/13#issuecomment-66777407

### CODE REVIEW

**Comment by heff** [comment]
@tomjohnson916, if you do end up working on the swf for BC hack week, take this one into consideration.

**Comment by ange007** [comment]
To release 5 versions it is planned to include this function?

**Comment by yangshenys** [comment]
How is it going? @heff

**Comment by ange007** [comment]
Chances of switching on of this function in the next versions aren't present?

**Comment by githubzhaoqian** [comment]
I can't wait...... It's looking forward to it.Why not appear in version 5?

**Comment by mmcc** [comment]
We've let this one linger for waay too long, so my apologies on that, but we're just not prepared to support or include such a feature in Videojs at this time. Sorry everyone, but thank you so much for the contributions @ange007.

**Comment by degtyaryov** [comment]
My implementation works fine on production more than a year. From user complaints were not.

**Pull request closed without merging**
