### PR TITLE
ci: test Node.js 6, 8, 10 and 11

### PR DESCRIPTION
**Pull request by DanielRuf**
## Description
Please describe the change as necessary.
If it's a feature or enhancement please be as detailed as possible.
If it's a bug fix, please link the issue that it fixes or describe the bug in as much detail.

## Specific Changes proposed
`lts/*` uses only the last LTS branch but not the others. Currently Node.js 6, 8 and 10 are LTS. See https://github.com/nodejs/Release/blob/master/README.mdy

## Requirements Checklist
- [ ] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Change has been verified in an actual browser (Chome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](http://jsbin.com/axedog/edit?html,output))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by gkatsev** [comment]
Thanks for the PR, however, because we test in browsers, we don't need to run against multiple versions of node.

**Comment by DanielRuf** [comment]
What about the dependencies and contributors and Node.js projects which require/import video.js and bundle files using webpack?

**Comment by DanielRuf** [comment]
See https://www.npmjs.com/package/video.js so there are definitely people who consume video.js using Node.js and we for example require the source files and build them ourself for treeshaking, different (vendor) bundles and so on.

**Comment by DanielRuf** [comment]
Which is not relevant for devs like me who bundle it themself with webpack and babelify and treeshake the code (as we often do with frontend frameworks).

**Comment by DanielRuf** [comment]
Are consumers allowed to use Node.js or should it be set to `node >= 8` in the `engines` field of package.json?

Just asking to also make sure that we can move forward with the required Node.js version for contributors and video.js building itself.

**Comment by gkatsev** [comment]
There's no need to babelify Video.js, fwiw, as we compile our code down to ES5. We also bundle all the library code into a single file via rollup. We have .es.js for esmodules and import statements, .cjs.js for commonjs and require statements. Those two files don't have dependencies included.

If you require Video.js directly in node.js as opposed to shipping it to the web, you're basically going to get a function that does nothing. This can be useful if you're doing server-side rendering and then rehydrate client-side. So you want to import Video.js but have it basically do nothing, which is what it does.

The version of Node is mostly relevant just for building and developing Video.js. Our [nvmrc file](https://github.com/videojs/video.js/blob/master/.nvmrc) (and I guess the travis.yml) serves as documentation of which node version to use.

**Pull request closed without merging**
