### PR TITLE
Fixed undefined error.

### PR DESCRIPTION
**Pull request by ksjun**
There is no Component.registerTech(). It's Tech.registerTech()

### CODE REVIEW

**Comment by pam** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 1ad980514817cd9d7e9db08e8d96df748e98163c
Build details: https://travis-ci.org/pam/video.js/builds/91346241

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by gkatsev** [comment]
Ha, thanks. Copypasta :/

**Comment by gkatsev** [comment]
@pam retry

**Comment by gkatsev** [comment]
Thanks.

**Comment by pam** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 1ad980514817cd9d7e9db08e8d96df748e98163c
Build details: https://travis-ci.org/pam/video.js/builds/91398600

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Pull request closed without merging**
