### PR TITLE
queue playback events when playback rate is zero and seeking is true (vjs5)

### PR DESCRIPTION
**Pull request by squarebracket**
This is a clone of PR #5024 made against the 5.x branch.

Needed because the [related PR for contrib-hls](https://github.com/videojs/videojs-contrib-hls/pull/1374) will also link against vjs5.

### CODE REVIEW

**Comment by gkatsev** [comment]
Maybe we drop vjs 5 support with this PR for contrib-hls? thoughts @forbesjo @OshinKaramian @mjneil?
I'd prefer not having to do a minor release of the 5.x line.

**Comment by forbesjo** [comment]
I don't think we should update video.js 5 for this however as noted in the other PR (https://github.com/videojs/video.js/pull/5024#issuecomment-378820010) we should make sure that the change in videojs-contrib-hls is backwards compatible

**Comment by forbesjo** [comment]
Upon further discussion we'll make it very clear in the contrib-hls README and package.json which version of video.js this change is compatible with.

**Comment by gkatsev** [comment]
Going to close this until/if we decide that we want to make this change.

**Pull request closed without merging**
