### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by mattbrundage**
HTML character notation "nbsp" wasn't visible

### CODE REVIEW

**Comment by thijstriemstra** [comment]
already fixed in #4880

**Comment by gkatsev** [comment]
Thanks for the PR but as @thijstriemstra mentioned, it's fixed in master now via #4880.

**Comment by mattbrundage** [comment]
Excellent.

**Comment by gkatsev** [comment]
Thanks you both :)

**Pull request closed without merging**
