### PR TITLE
Added vjs.extend method

### PR DESCRIPTION
**Pull request by carpasse**
Added ```extend``` method to be able to easily merge options when you  create a plugin.

### CODE REVIEW

**Comment by heff** [comment]
@carpasse, FYI, there's a related conversation in #1232 if you have any thoughts.

**Comment by heff** [comment]
Just commenting on the status of this. We're working on [a major refactor for 5.0](https://github.com/videojs/video.js/pull/1976). As part of that we're going to be reorganizing utils, and pulling in lodash to replace a lot of the custom functions. This may or may not be affected by that, but we need to wait to see how that plays out first. #1232 is where discussions around that will happen.

**Comment by mmcc** [comment]
@carpasse So I think we've landed on pulling in [lodash](http://lodash.com) for whatever utilities we can, so this is a pretty prime usage. I think step 1 is to make use of your extensive tests to ensure that it's a drop in replacement (should be), and if all is well have you start the process of importing / exporting lodash methods.

@heff is currently working on splitting apart the lib stuff into different files, so you guys might want to coordinate on timing of this.

**Comment by gkatsev** [comment]
Actually, for extend specifically, we should use `Object.assign`. There's a shim for it available on npm: https://www.npmjs.com/package/object.assign
It allows local usage of object.assign without shimming it globally:
```js
var assign = Object.assign || require('object.assign');
```
I think this is the best course of action, if possible. lodash has a lot of useful stuff but if the language has it (or is getting it), we should try and use it instead.

**Comment by heff** [comment]
Ok, so as part of the 5.0 work we exported [videojs.mergeOptions](https://github.com/videojs/video.js/blob/fdd133906cc1a33ee81303989555cca843d41898/src/js/video.js#L253), and we'll be exporting `videojs.assign` also. @carpasse I think that covers everything here, but if it doesn't let me know and we'll reopen. I'm just trying to move quickly through the remaining 5.0 tasks so we can get it released.

**Comment by carpasse** [comment]
@heff I thing it looks good. Thanks for the efforts

**Pull request closed without merging**
