### PR TITLE
fix: remove button outlines

### PR DESCRIPTION
**Pull request by Michael77**
## Description
This removes the button outlines that look out of place around the play and volume controls (and perhaps others)

## Specific Changes proposed
Removes the button outlines for the vjs-control class

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Change has been verified in an actual browser (Chome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](http://jsbin.com/axedog/edit?html,output))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by gkatsev** [comment]
Thanks for the PR. However, removing these outlines will make the player less accessible and that isn't what we're striving for. Instead, we recommend you implement this yourself if you do not want the outlines in your player. However, for the sake of accessibility, I would urge you not to do so.

**Comment by Michael77** [comment]
In what way would it make it less accessible? Youtube and Vimeo don't use button outlines around their player controls, which is worth mentioning.

**Comment by mister-ben** [comment]
It's important for keyboard control. See e.g. http://www.outlinenone.com

It's not so much we can't remove it as we shouldn't without an alternative. We could have nicer focus styles. YouTube's approach is to only style for focus when there's been keyboard interaction, which seems a reasonable compromise between aesthetics and accessibility.

**Comment by gkatsev** [comment]
We do want to make it so that it is only shown for keyboard usage but, unfortunately, we haven't gotten a chance to get that in yet.

**Comment by Michael77** [comment]
Thank you for the informative replies, I will read into this topic more.

**Comment by gkatsev** [comment]
Thanks @mister-ben for replying. I should've been more informative about this in my initial reply.

**Pull request closed without merging**
